import { B, Img, MAGENTA, MUTED, Stage, T } from "../pdmaPrimitives";
import { pdmaAssets } from "../../pdmaAssets";
import { pdmaGeometry } from "../../pdmaGeometry";
const S = pdmaAssets.slide09Root;
const sources = [["CRM", "Customer data", "ddd5d.svg"], ["PRODUCT USAGE", "Behavioral data", "cda12.svg"], ["SUPPORT", "Support tickets", "e2600.svg"], ["ACCOUNT HEALTH", "Billing & health data", "defdd.svg"]] as const;
export function Slide09(){ const g=pdmaGeometry.slide09; return <Stage><div style={{position:"absolute",left:g.business.x,top:g.business.y,width:g.business.width,height:g.business.height,background:"#15181b",border:"1px solid #2d3136",borderRadius:14}}><T geometry={g.businessInner.label} weight={600} color={MAGENTA}>BUSINESS PROBLEM</T><T geometry={g.businessInner.body} weight={600}>Customer retention teams spend too{"\n"}much time manually identifying{"\n"}churn risk across fragmented{"\n"}enterprise systems.</T><B geometry={g.businessInner.divider} bg={MUTED}/><T geometry={g.businessInner.driverLabel} weight={600} color={MUTED}>PRIMARY VALUE DRIVER</T><T geometry={g.businessInner.primary} weight={600} color={MAGENTA}>INCREASE REVENUE</T><T geometry={g.businessInner.secondary} weight={600}>+ STREAMLINE OPERATIONS</T></div>
 {sources.map(([a,b,icon],i)=>{const c=g.sourceCards;return <div key={a} style={{position:"absolute",left:c.x,top:c.y+i*c.pitch,width:c.width,height:c.height,background:"#1a1c1f",border:"1px solid #2d3136",borderRadius:10}}><B geometry={c.tile} bg="#240e1d" radius={8}/><Img src={`${S}/${icon}`} geometry={c.icon}/><T geometry={c.title} weight={600}>{a}</T><T geometry={c.body} color={MUTED}>{b}</T><Img src={`${S}/a0c4b.svg`} geometry={c.arrow}/></div>})}
 {["885aa.svg","d98bc.svg","ca18f.svg","394fd.svg","1b2ef.svg"].map((a,i)=><Img key={a} src={`${S}/${a}`} geometry={g.pipeline[i]}/>)}
 <div style={{position:"absolute",left:g.identify.x,top:g.identify.y,width:g.identify.width,height:g.identify.height,background:"#240e1d",border:`1px solid ${MAGENTA}`,borderRadius:14}}><Img src={`${S}/86e75.svg`} geometry={g.identify.icon}/><T geometry={g.identify.title} weight={600}>IDENTIFY</T><T geometry={g.identify.body}>Detect meaningful{"\n"}churn-risk patterns{"\n"}across enterprise{"\n"}customer data.</T></div><div style={{position:"absolute",left:g.recommend.x,top:g.recommend.y,width:g.recommend.width,height:g.recommend.height,background:"#1a1c1f",border:`1px solid ${MAGENTA}`,borderRadius:14}}><Img src={`${S}/563bf.svg`} geometry={g.recommend.icon}/><T geometry={g.recommend.title} weight={600}>RECOMMEND</T><T geometry={g.recommend.body}>Recommend an approved{"\n"}intervention to the{"\n"}responsible team.</T></div>
 <B geometry={g.connection.rule} bg={MAGENTA}/><T x={g.connection.arrow.x} y={g.connection.arrow.y} size={g.connection.arrow.size} color={MAGENTA}>→</T><T geometry={g.productSignal} weight={600} color={MUTED}>PRODUCT SIGNAL  →  PROBLEM  →  RECOMMENDED INTERVENTION</T><T geometry={g.productQuestion.label} weight={600} color={MAGENTA}>PRODUCT QUESTION</T><B geometry={g.productQuestion.divider} bg={MUTED}/><T geometry={g.productQuestion.question} weight={600}>How much authority should this agent have?</T><B geometry={g.takeaway.rule} bg={MUTED}/><B geometry={g.takeaway.accent} bg={MAGENTA}/><T geometry={g.takeaway.copy} weight={600}>HOW DO WE TURN THIS BUSINESS CASE INTO A PRODUCTION-READY ENTERPRISE PRODUCT?</T></Stage> }
