export const caseStudyCardCatalog = {
  aa: { slug: "aa", eyebrow: "Related Case Study", title: "Saving American Apparel With Digital Commerce", summary: "A global commerce and inventory transformation that connected stores, factory, and web on one operating model.", href: "/work/aa", image: { src: "/aa/hero-aa-01.png", alt: "American Apparel digital commerce transformation" } },
  bi: { slug: "bi", eyebrow: "Related Case Study", title: "Boehringer Ingelheim: 1st B2B Adobe Cloud Commerce", summary: "A global systems transformation requiring product direction, operating-model clarity, and disciplined integration decisions.", href: "/work/bi", image: { src: "/bi/hero-bi-01.png", alt: "Boehringer Ingelheim global commerce transformation hero image" } },
  cbdistillery: { slug: "cbdistillery", eyebrow: "Related Case Study", title: "CBDistillery's: From De-Banked to $40m", summary: "A commerce and payments transformation that made recurring billing, subscriptions, and retention programs work cleanly.", href: "/work/cbdistillery", image: { src: "/cbdistillery/hero-cbd-01.png", alt: "CBDistillery commerce transformation" } },
  cps: { slug: "cps", eyebrow: "Related Case Study", title: "CPS Energy: Smart Streetlight & Smart City Operations", summary: "A connected operating model that joined resident reporting, city systems, and field workflow into one accountable service loop.", href: "/work/cps", image: { src: "/cps/hero-cps-01.png", alt: "CPS Energy smart streetlight operations" } },
  cwg: { slug: "cwg", eyebrow: "Related Case Study", title: "Chicks With Guns: Building a Digital Music Magazine", summary: "A founder-led digital publication built around product direction, editorial standards, and contributor operations.", href: "/work/cwg", image: { src: "/founder/cwg/hero-cwg-01.png", alt: "Chicks With Guns digital music magazine" } },
  dtv01: { slug: "dtv01", eyebrow: "Related Case Study", title: "Turning DIRECTV's Slow Offer Engine to a Revenue Machine", summary: "A revenue platform and operating model that made DIRECTV offers faster, clearer, and repeatable.", href: "/work/dtv01", image: { src: "/dtv01/hero-dtv-01.png", alt: "DIRECTV revenue platform" } },
  dtv02: { slug: "dtv02", eyebrow: "Related Case Study", title: "Leading the Launch of DIRECTV Everywhere", summary: "A cross-platform streaming product aligned across teams, devices, content, and authentication.", href: "/work/dtv02", image: { src: "/dtv02/hero-dtv02-01.png", alt: "DIRECTV Everywhere launch" } },
  foh: { slug: "foh", eyebrow: "Related Case Study", title: "Turning Frederick's Into Celebrity-Driven DTC", summary: "A lean Shopify Plus relaunch built for celebrity traffic, campaign velocity, and a cleaner operating model.", href: "/work/foh", image: { src: "/foh/hero-foh-01.png", alt: "Frederick's of Hollywood and Megan Fox relaunch campaign imagery" } },
  k2: { slug: "k2", eyebrow: "Related Case Study", title: "Headless/Composable Commerce for 9 K2 Brands", summary: "A multi-brand commerce architecture that connected shared systems, brand experience, and migration strategy.", href: "/work/k2", image: { src: "/k2/hero-k2-01.png", alt: "K2 multi-brand commerce architecture" } },
  lego: { slug: "lego", eyebrow: "Related Case Study", title: "LEGO's Digital Transformation With BCG", summary: "Product management and solution architecture that turned transformation strategy into shippable behavior.", href: "/work/lego", image: { src: "/lego/hero-lego-01.png", alt: "LEGO digital transformation" } },
  method: { slug: "method", eyebrow: "Related Case Study", title: "Method's Digital Commerce Transformation", summary: "A composable commerce operating model that made brand growth repeatable across the portfolio.", href: "/work/method", image: { src: "/method/hero-method-01.png", alt: "Method digital commerce transformation" } },
  mm: { slug: "mm", eyebrow: "Related Case Study", title: "Mrs. Meyer's DTC Commerce Launch", summary: "A direct-to-consumer launch that turned a home-care brand into a repeatable commerce pattern.", href: "/work/mm", image: { src: "/mm/hero-mm-01.png", alt: "Mrs. Meyer's DTC commerce launch" } },
  modere: { slug: "modere", eyebrow: "Related Case Study", title: "Winning Awards and Making $1B With Modere", summary: "A composable commerce platform built to scale markets, content, and mobile without rebuilding the stack each time.", href: "/work/modere", image: { src: "/modere/hero-modere-01.png", alt: "Modere composable commerce platform hero image" } },
  murad: { slug: "murad", eyebrow: "Related Case Study", title: "Murad's Digital Commerce Transformation", summary: "A connected commerce experience that aligned the brand, platform, and customer journey.", href: "/work/murad", image: { src: "/murad/hero-murad-01.png", alt: "Murad digital commerce transformation" } },
  newyorklife: { slug: "newyorklife", eyebrow: "Related Case Study", title: "New York Life's CoreCMS Launch", summary: "A governed publishing platform that made digital operations consistent across 12,000+ sites.", href: "/work/newyorklife", image: { src: "/newyorklife/hero-nyl-01.png", alt: "New York Life CoreCMS launch" } },
  zevo: { slug: "zevo", eyebrow: "Related Case Study", title: "Interactive Internet TV Before it was Mainstream", summary: "A founder-led product and platform direction story built around validation, roadmap, and go/no-go decisions.", href: "/work/zevo", image: { src: "/founder/zevo/hero-zevo-01.png", alt: "ZEVO interactive internet TV" } },
} as const

export type CaseStudySlug = keyof typeof caseStudyCardCatalog
export type CaseStudyCardCatalogEntry = (typeof caseStudyCardCatalog)[CaseStudySlug]
