import type { CaseStudyRevampData } from "./types"

export type CpsSolutionContent = {
  residentExperience: {
    eyebrow: string
    title: string
    copy: string
    points: string[]
    gallery: Array<{ src: string; alt: string }>
  }
  flow: { eyebrow: string; title: string; copy: string }
  closing: string
}

export const cpsSolutionContent: CpsSolutionContent = {
  residentExperience: {
    eyebrow: "Resident Experience",
    title: "A Front Door That Closes the Loop",
    copy: "The resident experience replaced a repeat-call loop with a digital reporting path. Residents could identify the affected streetlight, submit the issue with location context, and move the request directly into the operating workflow.",
    points: ["Map-based streetlight identification", "Digital issue submission", "Location and problem details captured at intake", "A clearer path into CPS Energy's repair workflow", "Reduced dependence on repeat phone calls"],
    gallery: [
      { src: "/cps/product-cps-01.png", alt: "CPS Energy map showing a selected streetlight and the Report Streetlight Issue action" },
      { src: "/cps/product-cps-02.png", alt: "CPS Energy Report Streetlight Issue tool with map-based reporting instructions" },
      { src: "/cps/product-cps-03.png", alt: "CPS Energy streetlight issue form for submitting customer and outage details" },
    ],
  },
  flow: { eyebrow: "Operating Model", title: "The Exact Workflow That Closed the Repair Loop", copy: "The resident interface, system workflow, dispatch process, field execution, closure, and follow-up were designed as one accountable service loop." },
  closing: "The value did not come from adding another isolated tool. It came from creating one operating model that CPS Energy and Dalkia could run from the first report through the completed repair.",
}

export const caseStudy: CaseStudyRevampData = {
  slug: "cps",
  breadcrumbCurrent: "CPS Energy",
  metadata: { title: "CPS Energy: Smart Streetlight & Smart City Operations", description: "I led the product and program work that connected resident reporting, operational systems, and field workflow into one accountable CPS Energy service loop.", image: { src: "/cps/hero-cps-01.png", alt: "CPS Energy streetlight operations in San Antonio across a network of more than 225,000 streetlights", width: 1440, height: 582 } },
  hero: {
    eyebrow: "SAP · Field Operations · Service Design · Systems Integration · Smart City · Public Utilities",
    title: "CPS Energy: Smart Streetlight & Smart City Operations",
    intro: "San Antonio’s streetlight repair process was failing in public. Residents reported the same outages repeatedly, work orders were lost between CPS Energy, Dalkia, SAP, dispatch, and field crews, and a repair could take roughly three weeks. I led the product and program work that connected the resident experience, operational systems, and field workflow into one accountable service loop—cutting repair calls by 73%, truck rolls by 43%, and repair windows to 1–4 days across 225K+ streetlights.",
    metrics: [{ value: "43", suffix: "%", label: "Fewer Truck Rolls" }, { value: "1–4", label: "Day Repair Window" }, { value: "225K", suffix: "+", label: "Streetlights" }],
    image: { kind: "image", src: "/cps/hero-cps-01.png", alt: "CPS Energy streetlight operations in San Antonio across a network of more than 225,000 streetlights", aspectRatio: "16/9" },
  },
  productionQuote: { quote: "For us, this is more than just a streetlight program, it's about creating a safer, greener, and more connected San Antonio. By embracing smart technologies, we are enhancing public safety, improving energy efficiency, and paving the way for a more sustainable future.", attributionTitle: "Richard Medina", attributionSubtitle: "Chief Energy Delivery Officer, CPS Energy", avatarSrc: "/cps/cps-richard-medina-tinified.png" },
  executiveBrief: {
    eyebrow: "At-a-Glance", title: "Smart City Operations", copy: "I led a $2M product and program transformation across CPS Energy and Dalkia, coordinating a 15-person team across two organizations and six integrations to rebuild the streetlight repair loop from resident intake through SAP, dispatch, field execution, closure, and follow-up.", role: "Program & Product Lead", client: "CPS Energy", timeline: "August 2024–April 2025 · 8 months", teamStakeholders: "15 people across CPS Energy and Dalkia", budgetScale: "$2M program budget · 225K+ streetlights · 1.5 million residents", systemsTechnology: "6 system integrations · SAP · IVR · field iPad workflow · resident reporting · telematics · Maximo/MDS", tools: [{ label: "SAP", icon: "/tool-icons/svg/sap-logo.svg" }, { label: "CPS Energy", icon: "/tool-icons/svg/cps-energy-logo.svg" }, { label: "System Integration", icon: "/tool-icons/svg/icon-system.svg" }], problem: "A broken streetlight could remain unresolved for roughly three weeks. Resident reports, SAP work orders, dispatch decisions, field activity, follow-up orders, and closure updates were fragmented across organizations and systems.", mandate: "Create one end-to-end service loop—from the first report or streetlight alert through dispatch, repair, closure, and follow-up—so work no longer disappeared between handoffs.", whatIChanged: "I mapped the complete resident-to-repair journey, defined the resident reporting experience, aligned CPS Energy and Dalkia around one operating model, prioritized SAP and field-workflow integration, and used a proof of concept to move the organization from debate into deployment.", outcome: "The solution was successfully launched and deployed. Repair calls fell 73%, truck rolls fell 43%, repair windows dropped from approximately three weeks to 1–4 days, and the service directly supported 1.5 million San Antonio residents.", facts: [{ icon: "role", label: "Role", value: "Program & Product Lead" }, { icon: "client", label: "Client", value: "CPS Energy" }, { icon: "timeline", label: "Timeline", value: "Aug 2024–Apr 2025 · 8 months" }, { icon: "team", label: "Team", value: "15 people across two organizations" }, { icon: "budget", label: "Budget / Scale", value: "$2M · 225K+ streetlights" }, { icon: "systems", label: "Integrations", value: "6 system integrations" }] },
  challenge: { eyebrow: "Problem Statement", title: "Homes in Darkness", paragraphs: ["San Antonio residents were dealing with dark streets, slow repair timelines, and a support experience that gave them no confidence an outage would be resolved. The problem was bigger than maintenance. The service loop was fragmented across resident intake, 311 and call-center channels, IVR, SAP, dispatch, field crews, follow-up orders, and closure.", "Ownership was divided across CPS Energy and Dalkia, but nobody owned the complete journey. Residents reported the same outage repeatedly because they could not see status. Field crews could arrive without current work-order information. Follow-up work could disappear between teams. Operations lacked one reliable view of the repair lifecycle across more than 225,000 streetlights.", "Dark streets and delayed repairs became local-news material. The program therefore had to solve the operational problem and restore public confidence: one intake path, one accountable workflow, and one closed loop from report to repair."], visual: { kind: "youtube", videoId: "Ch9cUuG95qI", aspectRatio: "16/9" }, caption: "Local news documented the streetlight service failure before the modernization program delivered a connected repair loop." },
  ownership: { eyebrow: "What I Owned", title: "Program & Product Lead", summary: "A $2M program. Fifteen people across two organizations. Six integrations and 225K+ streetlights. I owned the product direction, program structure, service design, and end-to-end accountability that turned a visible public-service failure into a deployed operating model.", decisions: [{ title: "Mapped the Entire Resident-to-Repair Journey", copy: "I traced the failure across reporting, IVR, SAP work-order creation, dispatch, simple and complex repair paths, field completion, system closure, and follow-up." }, { title: "Defined the Resident Reporting Experience", copy: "I led the product and UX direction for a resident-facing reporting experience that let people identify the affected streetlight and submit the issue digitally." }, { title: "Aligned CPS Energy and Dalkia Around One Service Model", copy: "I established shared ownership, clarified handoffs, and kept the work organized around one resident-to-repair outcome." }, { title: "Connected Field Work to the System of Record", copy: "I drove alignment around the field iPad workflow and SAP integration so crews could receive work, complete repairs, trigger follow-up work, and close the loop." }, { title: "Used the Proof of Concept as a Forcing Function", copy: "I partnered with engineering to turn abstract integration debates into observable system behavior and move the program into successful delivery." }] },
  solution: { eyebrow: "Solution", title: "One Service Loop From Report to Repair", copy: "One front door for residents. One operational flow across CPS Energy and Dalkia. One accountable path through intake, SAP, dispatch, field work, closure, and follow-up.", architecture: [
    { eyebrow: "Resident Experience", title: "Find the Exact Streetlight", copy: "Residents could select the affected light on an interactive map and move directly into issue reporting.", bullets: ["Streetlight identified by location", "Digital issue submission", "Less dependence on repeat calls"], image: { src: "/cps/product-cps-01.png", alt: "CPS Energy map showing a selected streetlight and the Report Streetlight Issue action", width: 900, height: 1406 } },
    { eyebrow: "Resident Experience", title: "Capture the Right Context", copy: "The reporting tool carried location and problem details into the service workflow so the request could be acted on.", bullets: ["Resident and outage details", "Clear path into operations", "Connected to the repair lifecycle"], image: { src: "/cps/product-cps-02.png", alt: "CPS Energy Report Streetlight Issue tool with map-based reporting instructions", width: 900, height: 1406 } },
    { eyebrow: "Resident Experience", title: "Close the Resident Loop", copy: "A structured issue form connected the resident-facing experience to the operational work required to resolve the outage.", bullets: ["Relevant issue information captured", "Field work could follow the report", "Repair status could return to the service path"], image: { src: "/cps/product-cps-03.png", alt: "CPS Energy streetlight issue form for submitting customer and outage details", width: 900, height: 1406 } },
  ], summary: cpsSolutionContent.closing },
  impact: { eyebrow: "Impact", title: "The Results I Drove", intro: "The program improved the three parts of the service that mattered most: resident access, operational coordination, and field execution.", editorialImage: { src: "/cps/hero-cps-04.png", alt: "CPS Energy streetlight operations impact", width: 1440, height: 386 }, metrics: [{ value: "73", suffix: "%", label: "Fewer Repair Calls", detail: "Reduction after digital intake and closed-loop operations" }, { value: "43", suffix: "%", label: "Fewer Truck Rolls", detail: "Reduction through better dispatch and field coordination" }, { value: "1–4", label: "Day Repair Window", detail: "Reduced from approximately three weeks" }, { value: "225K", suffix: "+", label: "Streetlights", detail: "Network in scope" }], transformation: { eyebrow: "Transformation", title: "From public failure to one measurable operating model", rows: [{ problem: "Inefficient resident intake", decision: "Map-based resident experience connected to the operating workflow", outcome: "One clear front door helped reduce repeat repair calls by 73%." }, { problem: "Disconnected field work", decision: "Field iPad workflow aligned to the repair lifecycle", outcome: "Repair windows fell from approximately three weeks to 1–4 days and truck rolls fell 43%." }, { problem: "Fragmented ownership and systems", decision: "Program structure, SAP prioritization, and proof-of-concept validation", outcome: "The solution successfully launched and deployed, serving 1.5 million San Antonio residents." }] } },
  evidence: { eyebrow: "Delivery Proof", title: "What the Work Actually Produced", intro: "The work connected a visible city problem to a deployed and accountable operating model.", testimonial: { quote: "This is the city's first official initiative to widely install solar-powered LED street lights within city limits. Together we are lighting the path to a brighter future!", attributionTitle: "Ron Nirenberg", attributionSubtitle: "Mayor, San Antonio, Texas", avatarSrc: "/cps/ron-nirenberg.webp" }, validationItems: [] },
  recognition: { eyebrow: "Recognition", title: "From Public Failure to Smart-City Recognition", intro: "The evidence spans the full program arc: public reporting of the streetlight problem, official records and project coverage, and recognition of the deployed operating model through the 2025 Smart 20 Award.", featured: { media: { kind: "youtube", videoId: "GZMHsAIH1Os", aspectRatio: "16/9" }, title: "San Antonio New Low-Carbon Streetlights", date: "August 20, 2025", summary: "New solar streetlights set to go up across San Antonio as CPS Energy partners to modernize the city's streetlight network", tags: ["Press", "ABC News"] }, rows: [{ publisher: "MaryScottNabers.com", date: "April 23, 2025", summary: "Texas claimed 5 of the top 20 smart city projects globally, with San Antonio among the honorees at the 2025 Smart 20 Awards", pdfHref: "/cps/files/20250423_CPSE_MSN.pdf" }, { publisher: "TerraGo Technologies", date: "April 15, 2025", summary: "CPS Energy's streetlight and smart city program wins the 2025 Smart 20 Award for innovation, sustainability, and connected operations", pdfHref: "/cps/files/20250415_CPSE_TerraGo.pdf" }, { publisher: "San Antonio Report", date: "August 30, 2024", summary: "San Antonio contracts with Dalkia Energy to install 400 new solar-powered streetlights, addressing gaps in street lighting and improving public safety", pdfHref: "/cps/files/20240830_CPSE_SAReport.pdf" }, { publisher: "CPS Energy Board of Trustees", date: "March 25, 2024", summary: "Board meeting agenda covering the Smart City and streetlight modernization program", pdfHref: "/cps/files/20240325_CPSE_SACityCouncilAgenda.pdf" }, { publisher: "News4SanAntonio (NBC)", date: "March 18, 2024", summary: "Northeast San Antonio residents go without street lighting for months, exposing the urgency of CPS Energy's modernization program", pdfHref: "/cps/files/20240318_CPSE_NBC.pdf" }, { publisher: "Digi.City", date: "February 20, 2024", summary: "Smart Cities Connect announces the 2024 Smart 20 Awards, recognizing the top 20 most innovative smart city projects worldwide", pdfHref: "/cps/files/20240220_CPSE_DigiCity.pdf" }] },
  relatedStudies: [{ eyebrow: "Related Study 01", title: "New York Life's Scalable Product Platform", summary: "A platform modernization story about turning fragmented enterprise needs into a governed operating model.", href: "/work/newyorklife", image: { src: "/newyorklife/hero-nyl-02.png", alt: "New York Life scalable product platform" } }, { eyebrow: "Related Study 02", title: "Boehringer Ingelheim: 1st B2B Adobe Cloud Commerce", summary: "A global systems transformation requiring product direction, operating-model clarity, and disciplined integration decisions.", href: "/work/bi", image: { src: "/bi/hero-bi-01.png", alt: "Boehringer Ingelheim global B2B commerce program" } }],
  finalCta: { eyebrow: "", title: "", copy: "" },
}

caseStudy.executiveBrief.tools = [
  { label: "Figma", icon: "/tool-icons/svg/figma-logo.svg" },
  { label: "Azure", icon: "/tool-icons/svg/azure-logo.svg" },
  { label: "SAP", icon: "/tool-icons/svg/sap-logo.svg" },
  { label: "Smartsheet", icon: "/tool-icons/svg/smartsheet-logo.svg" },
]
