const asset = (slide: string, file: string) => `/pdma2026/${slide}/${file}`;
import { motion, useReducedMotion } from "motion/react";
import { PdmaSlideCanvas } from "../PdmaPresentationShell";
import { PdmaSlideBody } from "./PdmaSlideBody";

function Layer({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) { const reduced = useReducedMotion(); return <motion.div className={className} initial={reduced ? false : { opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: reduced ? 0 : .55, delay: reduced ? 0 : delay, ease: "easeOut" }}>{children}</motion.div>; }
function ImageLayer({ src, className, alt = "", delay = .12, opacity = 1 }: { src: string; className: string; alt?: string; delay?: number; opacity?: number }) { const reduced = useReducedMotion(); return <motion.img className={className} src={src} alt={alt} initial={reduced ? false : { opacity: 0, scale: 1.025 }} animate={{ opacity, scale: 1 }} transition={{ duration: reduced ? 0 : .8, delay: reduced ? 0 : delay, ease: "easeOut" }} />; }
export function Slide01() { return <PdmaSlideCanvas><div className="pdma-slide-surface pdma-s01"><ImageLayer className="s01-wide" src={asset("slide-01", "title-atmosphere.png")} opacity={.75} /><ImageLayer className="s01-orb" src={asset("slide-01", "title-asterisk-scene.png")} delay={.15} opacity={.75} /><Layer className="s01-title-white"><h1>THE NEW PM</h1></Layer><Layer className="s01-title-magenta" delay={.08}><h1>OPERATING SYSTEM</h1></Layer><Layer className="s01-subtitle" delay={.16}><p>What stays uniquely human.<br/>What shifts to AI.</p></Layer><motion.i className="s01-speaker-rule" initial={{ scaleX: 0 }} animate={{ scaleX: 1 }} transition={{ duration: .45, delay: .28 }} /><Layer className="s01-speaker-name" delay={.3}><strong>Jim Markunas</strong></Layer><Layer className="s01-speaker-role" delay={.36}><span>Head of Product, Bytalos</span></Layer><motion.i className="s01-people-rule" initial={{ scaleY: 0 }} animate={{ scaleY: 1 }} transition={{ duration: .45, delay: .3 }} /><Layer className="s01-people" delay={.34}>PEOPLE<br/>AMPLIFY<br/>POSSIBILITY</Layer><motion.i className="s01-ai-rule" initial={{ scaleY: 0 }} animate={{ scaleY: 1 }} transition={{ duration: .45, delay: .38 }} /><Layer className="s01-ai" delay={.42}>AI<br/>EXPANDS<br/>WHAT’S<br/>POSSIBLE</Layer></div></PdmaSlideCanvas>; }

const slide03Copilot = [["H", "HUMAN"], ["P", "PROMPT"], ["M", "MODEL"], ["O", "OUTPUT"]] as const;
const slide03Agent = [["G", "GOAL"], ["A", "AGENT"], ["T", "TOOL / SYSTEM"], ["→", "ACTION"]] as const;
function Slide03Process({ items, accentIndex = -1 }: { items: readonly (readonly [string, string])[]; accentIndex?: number }) { return <div className="s03-process">{items.map(([glyph, label], index) => <div className={`s03-step ${index === accentIndex ? "is-accent" : ""}`} key={label}><div className="s03-step-circle">{glyph}</div><span>{label}</span>{index < items.length - 1 && <b>→</b>}</div>)}</div>; }
export function Slide03() { return <PdmaSlideCanvas><div className="pdma-slide-surface pdma-s03"><PdmaSlideBody className="pdma-slide-body-03"><ImageLayer className="s03-left" src={asset("slide-03", "02283.png")} /><ImageLayer className="s03-right" src={asset("slide-03", "44753.png")} delay={.2} /><section className="s03-panel s03-panel-copilot"><h2>C O P I L O T</h2><p className="s03-descriptor">A S S I S T S&nbsp;&nbsp; W I T H&nbsp;&nbsp; O U T P U T S</p><Slide03Process items={slide03Copilot} accentIndex={3}/><hr/><p className="s03-boundary-copy">Human remains the execution boundary.</p></section><section className="s03-panel s03-panel-agent"><h2>A G E N T</h2><p className="s03-descriptor">A C T S&nbsp;&nbsp; I N&nbsp;&nbsp; T H E&nbsp;&nbsp; R E A L&nbsp;&nbsp; W O R L D</p><Slide03Process items={slide03Agent} accentIndex={1}/><hr/><p className="s03-boundary-copy">AI can now cross the execution boundary.</p><p className="s03-capabilities">READ&nbsp;&nbsp; • &nbsp;&nbsp;WRITE&nbsp;&nbsp; • &nbsp;&nbsp;SEND&nbsp;&nbsp; • &nbsp;&nbsp;SPEND</p></section><i className="s03-panel-divider"/><div className="s03-takeaway"><i/> <strong>WHEN AI BECOMES AN OPERATOR, AUTHORITY BECOMES A PRODUCT DECISION.</strong></div></PdmaSlideBody></div></PdmaSlideCanvas>; }

export function Slide04() { return <PdmaSlideCanvas><div className="pdma-slide-surface pdma-s04"><PdmaSlideBody className="pdma-slide-body-04"><ImageLayer className="s04-wide" src={asset("slide-04", "0c14e.png")} /><ImageLayer className="s04-diagram" src={asset("slide-04", "bd2f1.png")} delay={.22} /><div className="s04-cards">{[["01","AUTOMATE","AI owns execution of bounded, repeatable work."],["02","AUGMENT","AI improves speed, synthesis, or quality while a human still decides."],["03","HUMAN-OWNED","Judgment, accountability, and authority stays human."]].map(([n,t,d],i)=><Layer key={n} delay={i*.1}><article><small>{n}</small><h2>{t}</h2><p>{d}</p><b>{i===0?"EXECUTION":i===1?"DECISION":"ACCOUNTABILITY"}</b></article></Layer>)}</div><div className="s04-takeaway"><i/>THE GOAL: BUILD THE RIGHT OPERATING MODEL FOR THE WORK.</div></PdmaSlideBody></div></PdmaSlideCanvas>; }

export function Slide05() { return <PdmaSlideCanvas><div className="pdma-slide-surface pdma-s05"><PdmaSlideBody className="pdma-slide-body-05"><img className="s05-wide" src={asset("slide-05", "51d1a.png")} alt=""/><img className="s05-orb" src={asset("slide-05", "9f2f3.png")} alt=""/><div className="s05-unclear">UNCLEAR PROBLEM.<br/>UNCLEAR OWNER.<br/>UNCLEAR AUTHORITY.</div><b className="s05-equals">=</b><strong className="s05-confusion">CONFUSION AT MACHINE SPEED.</strong></PdmaSlideBody></div></PdmaSlideCanvas>; }
