function Chrome({ footer, labels, fill }: { footer: string; labels: [string, string, string]; fill: string }) {
  return <><header className="pdma-header"><span className="pdma-event">PDMA 2026</span><div className="pdma-track"><span className="pdma-fill" style={{ width: fill }} /></div><span className="pdma-nav pdma-nav-ownership">{labels[0]}</span><b className="pdma-nav pdma-nav-bullet-1">•</b><span className="pdma-nav pdma-nav-judgment">{labels[1]}</span><b className="pdma-nav pdma-nav-bullet-2">•</b><span className="pdma-nav pdma-nav-automation">{labels[2]}</span></header><footer className="pdma-footer"><span className="pdma-footer-statement">{footer}</span><span className="pdma-footer-rule" /><img className="pdma-asterisk" src="/pdma2026/slide-02/canonical-asterisk.svg" alt="" /></footer></>;
}

export function Slide10() { return <div className="pdma-slide-surface pdma-b3 pdma-b3-10"><img className="readiness-mountains" src="/pdma2026/slide-10/0581d3e2-5eaa-4fa2-aa65-7272161757da.png" alt="" /><img className="readiness-walkway" src="/pdma2026/slide-10/0fe576ac-b4aa-42eb-9c74-288c239abc05.png" alt="" /><Chrome fill="70%" footer="PRODUCTION READINESS STARTS IN THE BACKLOG" labels={["BACKLOG", "CONTROLS", "OUTCOMES"]} /><small className="b3-eyebrow">FROM REQUIREMENTS TO REAL IMPACT</small><h1>DESIGN PRODUCTION READINESS<br /><em>INTO THE FEATURE.</em></h1><p className="b3-intro">Guardrails, human intervention, and success measures belong in the product requirements before development begins.</p><div className="readiness-cards">{[["01", "GUARDRAILS", "What must the product prevent or constrain?"], ["02", "HUMAN INTERVENTION", "When must a person review, approve, or take over?"], ["03", "SUCCESS MEASURES", "What proves the feature creates the intended outcome?"]].map(([n, title, text]) => <article key={title}><small>{n}</small><h2>{title}</h2><i /><p>{text}</p></article>)}</div><div className="operational-sequence"><b>OPERATIONALIZE IT AS PRODUCT WORK</b><span>01&nbsp; BACKLOG</span><span>→</span><span>02&nbsp; PRD</span><span>→</span><span>03&nbsp; ACCEPTANCE CRITERIA</span><span>→</span><span>04&nbsp; PRODUCTION</span></div><div className="b3-takeaway">IF IT MATTERS IN PRODUCTION, IT BELONGS IN THE PRODUCT DEFINITION.</div></div>; }

const agents = [["A", "AUTHORITY", "Who decides what the system may do?"], ["G", "GUARDRAILS", "What boundaries keep action safe?"], ["E", "EVIDENCE", "What proves the recommendation is sound?"], ["N", "NETWORK & INTEGRATIONS", "What systems and signals must connect?"], ["T", "TRANSFER & ESCALATION", "When and how does work return to people?"], ["S", "SUCCESS & ACCOUNTABILITY", "How will the team know it worked?"]];
export function Slide11() { return <div className="pdma-slide-surface pdma-b3 pdma-b3-11"><Chrome fill="76.666%" footer="6 QUESTIONS • 1 PRODUCTIZATION STANDARD" labels={["STANDARD", "PRODUCT", "GOVERN"]} /><h1>A.G.E.N.T.S.<br /><em>IS THE PRODUCT.</em></h1><p className="agents-support">Six product questions that turn an Agentic AI idea into something a team can safely build, test, and operate.</p><div className="agents-hub"><strong>1</strong><span>PRODUCTIZATION<br />STANDARD</span><i>SAME QUESTIONS.<br/>SAFER PRODUCTS.<br/>HIGHER CONFIDENCE.</i></div><div className="agents-cards">{agents.map(([letter, title, question], index) => <article key={letter} className={`agent-card agent-card-${index + 1}`}><b>{letter}</b><h2>{title}</h2><p>{question}</p></article>)}</div><div className="agents-rule"><b>USE A.G.E.N.T.S. TO</b> write better requirements, define operating boundaries, and make production behavior explicit.</div><div className="agents-takeaway">6 QUESTIONS • 1 PRODUCTIZATION STANDARD</div></div>; }

const requirements = [["REQUIREMENT", "What must the product be able to do?"], ["ACCEPTANCE CRITERIA", "How will we know it works?"], ["DECISION RECORD", "What decisions must remain explainable?"], ["SYSTEMS", "Which systems and data must connect?"], ["HUMAN-IN-THE-LOOP", "Where is review, intervention, or escalation required?"], ["KPI", "Which outcome proves the value?" ]];
const productRequirements = [["A","The agent may recommend a retention intervention, but cannot publish or launch it."],["G","Recommendations must stay within approved product surfaces and business rules."],["E","Keep a clear record of the recommendation, the inputs that drove it, and the final decision."],["N","Agent has read/write access to Salesforce, but cannot change customer payment data."],["T","CS Lead approval is required before an agent can update a customer's payment data."],["S","Measure retention lift, recommendation accuracy, false-positive rate, and human override rate."]];
export function Slide12() { return <div className="pdma-slide-surface pdma-b3 pdma-b3-12"><img className="requirements-plate" src="/pdma2026/slide-12/1d1865c5-5b25-4f1d-9106-9185a539fe56.png" alt="" /><img className="agents-tablet-art" src="/pdma2026/slide-12/4be2e216-d274-4069-b156-eb151877a784.png" alt="" /><img className="requirements-tablet-art" src="/pdma2026/slide-12/6a40e039-f704-4242-b3aa-aed23760b6f0.png" alt="" /><Chrome fill="83.333%" footer="6 QUESTIONS • 1 PRODUCTIZATION STANDARD" labels={["FRAMEWORK", "REQUIREMENTS", "PRODUCT"]} /><h1>TURN THE FRAMEWORK<br /><em>INTO PRODUCT REQUIREMENTS.</em></h1><p className="requirements-intro">A.G.E.N.T.S. changes how you<br/>write your backlog.</p><section className="commandment-tablet"><h2>A.G.E.N.T.S.<br/><small>FRAMEWORK</small></h2>{agents.map(([letter, title]) => <div key={letter}><b>{letter}</b><span>{title}</span></div>)}</section><div className="transform-arrow">→</div><section className="requirements-tablet"><h2>PRODUCT REQUIREMENTS</h2>{productRequirements.map(([letter, text]) => <div key={letter}><b>{letter}</b><span>→</span><p>{text}</p></div>)}</section><div className="b3-12-takeaway">FROM PRINCIPLES<br/>TO REQUIREMENTS.<br/>FROM POSSIBILITY<br/>TO PRODUCTION.</div></div>; }
