import { PdmaSlideCanvas } from "../PdmaPresentationShell";
import { pdmaAssets } from "../pdmaAssets";
import { pdmaGeometry } from "../pdmaGeometry";
import { B, Img, T } from "./pdmaSlidePrimitives";
const inventory = [["SYSTEMS", "What applications and\nplatforms are involved?", "icon-systems.svg"], ["DATA", "What information does the\nproduct depend on?", "icon-data.svg"], ["PEOPLE", "Who uses, owns, or\nsupports the workflow?", "icon-people.svg"], ["DEPENDENCIES", "What breaks if one\npart fails?", "icon-dependencies.svg"]] as const;
const owners = [["SYSTEM OWNER", "Who owns the system\nthe agent touches?", "icon-system-owner.svg"], ["DECISION OWNER", "Who owns the authority\nbeing delegated?", "icon-decision-owner.svg"], ["OUTCOME OWNER", "Who is accountable\nfor the result?", "icon-outcome-owner.svg"]] as const;
const WHITE = "#f2f2f2", MAGENTA = "#ff2fae";
export function Slide06() { const g = pdmaGeometry.slide06; return <PdmaSlideCanvas><div style={{ position: "absolute", inset: 0, width: 1920, height: 1080, overflow: "hidden", background: "#090909", color: WHITE }}><div style={{ position: "absolute", left: g.body.x, top: g.body.y, width: g.body.width, height: g.body.height, overflow: "hidden", background: "#040405" }}>
  <Img src={pdmaAssets.slide06.nebula} geometry={g.nebula} fit="cover"/><Img src={pdmaAssets.slide06.planet} geometry={g.planet}/><Img src={pdmaAssets.slide06.secondaryMoon} geometry={g.secondaryMoon}/><Img src={pdmaAssets.slide06.smallMoon} geometry={g.smallMoon}/><Img src={pdmaAssets.slide06.rings} geometry={g.rings} fit="cover"/>
  <T geometry={g.awareness} size={g.awareness.size} weight={500} color="#94969e" line={g.awareness.line} tracking={g.awareness.tracking}>MORE{"\n"}AWARENESS{"\n"}BETTER{"\n"}AUTONOMY</T><B geometry={g.awarenessRule} bg={MAGENTA}/><T geometry={g.inventoryHeading} size={17} weight={600} color={MAGENTA} tracking={5}>DO THE INVENTORY</T><T geometry={g.ownersHeading} size={17} weight={600} color={MAGENTA} tracking={5}>NAME THE OWNERS</T>
  <Img src={pdmaAssets.slide06.connectors} geometry={g.connector}/><B geometry={g.outerNode} bg="rgba(255,47,174,.2)" radius={99}/><B geometry={g.innerNode} bg="#f2f2f2" border={`3px solid ${MAGENTA}`} radius={99}/>
  {inventory.map(([title, body, icon], i) => { const c = g.inventoryCards, ig = c.icon[i]; return <div key={title} style={{ position: "absolute", left: c.x, top: c.y + i * c.pitch, width: c.width, height: c.height, boxSizing: "border-box", background: "rgba(14,17,20,.88)", border: "1.5px solid rgba(255,47,174,.65)", borderRadius: 12 }}><Img src={`/pdma2026/slide-06/${icon}`} geometry={ig}/><T x={c.title.x} y={c.title.y} w={c.title.width} size={c.title.size} weight={700} tracking={c.title.tracking}>{title}</T><T x={c.body.x} y={c.body.y} w={c.body.width} size={c.body.size} line={c.body.line}>{body}</T><T x={c.arrow.x} y={c.arrow.y} w={c.arrow.width} size={c.arrow.size} color={MAGENTA}>→</T><B x={c.node.x} y={c.node.y} w={c.node.width} h={c.node.height} bg="#f2f2f2" border={`2px solid ${MAGENTA}`} radius={99}/></div> })}
  {owners.map(([title, body, icon], i) => { const c = g.ownerCards, ig = c.icon[i]; return <div key={title} style={{ position: "absolute", left: c.x, top: c.y + i * c.pitch, width: c.width, height: c.height, boxSizing: "border-box", background: "rgba(31,3,20,.86)", border: "1.5px solid rgba(255,47,174,.8)", borderRadius: 12 }}><Img src={`/pdma2026/slide-06/${icon}`} geometry={ig}/><T x={c.title.x} y={c.title.y} w={c.title.width} size={c.title.size} weight={700} color={MAGENTA} tracking={c.title.tracking}>{title}</T><B x={c.rule.x} y={c.rule.y} w={c.rule.width} h={c.rule.height} bg="rgba(255,47,174,.55)"/><T x={c.body.x} y={c.body.y} w={c.body.width} size={c.body.size} line={c.body.line}>{body}</T><B x={c.node.x} y={c.node.y} w={c.node.width} h={c.node.height} bg="#f2f2f2" border={`2px solid ${MAGENTA}`} radius={99}/></div> })}
  <B geometry={g.takeawayRule} bg="rgba(92,94,102,.9)"/><B geometry={g.takeawayAccent} bg={MAGENTA}/><T geometry={g.takeaway} size={g.takeaway.size} weight={700}>AUTOMATION CHANGES EXECUTION. IT DOES NOT ERASE OWNERSHIP.</T>
 </div></div></PdmaSlideCanvas> }
