import { PdmaSlideCanvas } from "../PdmaPresentationShell";
import { PdmaSlideBody } from "./PdmaSlideBody";
import { Img } from "./pdmaSlidePrimitives";
import { pdmaGeometry } from "../pdmaGeometry";
import { motion } from "motion/react";
const ROOT = "/pdma2026/slide-02";
const ai = [["icon-search.svg", "Search & synthesis"], ["icon-drafting.svg", "Drafting & analysis"], ["icon-monitoring.svg", "Monitoring & coordination"]] as const;
const human = [["icon-ownership.svg", "Product ownership"], ["icon-tradeoffs.svg", "Priority & tradeoffs"], ["icon-authority.svg", "Authority & escalation"]] as const;
function List({ side, items, geometry }: { side: "ai" | "human"; items: readonly (readonly [string, string])[]; geometry: typeof pdmaGeometry.slide02.list }) { return <section className={`pdma-list pdma-list-${side}`} style={{ top: geometry.y + pdmaGeometry.slide02.contentShiftY, left: side === "ai" ? geometry.aiX : geometry.humanX, width: geometry.width, height: geometry.height }}><h2 style={{ fontSize: geometry.headingSize }}>{side === "ai" ? "SHIFTS TO AI" : "STAYS HUMAN"}</h2><span className="pdma-list-rule" style={{ top: geometry.ruleY, left: geometry.ruleX, width: geometry.ruleWidth }} />{items.map(([icon, label], index) => <div className="pdma-item" key={label} style={{ top: geometry.itemStart + index * geometry.itemPitch, height: geometry.itemHeight, fontSize: geometry.itemSize }}><span className="pdma-tile" style={{ width: geometry.tileSize, height: geometry.tileSize, marginRight: geometry.tileMarginRight }}><img src={`${ROOT}/${icon}`} alt="" /></span><span>{label}</span></div>)}</section>; }
function AmbientAsset({ asset, box, className, animate, transition }: { asset: string; box: { x: number; y: number; width: number; height: number }; className: string; animate: any; transition: any }) { return <div className={`s02-visual-box ${className}`} style={{ left: box.x, top: box.y, width: box.width, height: box.height }}><motion.img src={`${ROOT}/${asset}`} alt="" animate={animate} transition={transition} /></div>; }
export function Slide02() { const g = pdmaGeometry.slide02; const shift = g.contentShiftY; return <PdmaSlideCanvas><div className="pdma-slide-surface pdma-s02"><PdmaSlideBody className="pdma-slide-body-02"><List side="ai" items={ai} geometry={g.list}/><List side="human" items={human} geometry={g.list}/><AmbientAsset asset="slide-02-particle-field.png" box={{ ...g.particleField, y: g.particleField.y + shift }} className="s02-particle-field" animate={{ x: [0, 2, 0], opacity: [.68, .8, .68] }} transition={{ duration: 15, repeat: Infinity, ease: "easeInOut" }}/><AmbientAsset asset="slide-02-ai-sphere.png" box={{ ...g.aiSphere, y: g.aiSphere.y + shift }} className="s02-ai-sphere" animate={{ x: [0, 2, 0], y: [0, -2, 0], scale: [1, 1.006, 1] }} transition={{ duration: 14, repeat: Infinity, ease: "easeInOut" }}/><AmbientAsset asset="slide-02-human-sphere.png" box={{ ...g.humanSphere, y: g.humanSphere.y + shift }} className="s02-human-sphere" animate={{ x: [0, -2, 0], y: [0, 2, 0], scale: [1, 1.008, 1] }} transition={{ duration: 16, repeat: Infinity, ease: "easeInOut" }}/><Img geometry={{ ...g.cpu, y: g.cpu.y + shift }} className="s02-diagram-cpu" src={`${ROOT}/diagram-cpu.svg`} alt=""/><Img geometry={{ ...g.brain, y: g.brain.y + shift }} className="s02-diagram-brain" src={`${ROOT}/diagram-brain.svg`} alt=""/><div className="s02-boundary" style={{ top: g.boundary.y, width: g.boundary.width, height: g.boundary.height, gap: g.boundary.gap }}><strong>THE BOUNDARY IS NOT <span>HUMAN VS. AI.</span></strong><i/><strong>IT’S <span>DELEGATED WORK VS.</span> <span>HUMAN JUDGMENT.</span></strong></div></PdmaSlideBody></div></PdmaSlideCanvas>; }
