export const usaiiPresentationContent = {
  navigation: {
    previousAriaLabel: "Previous slide",
    nextAriaLabel: "Next slide",
    openTocAriaLabel: "Open slide table of contents",
    toggleFullscreenAriaLabel: "Toggle fullscreen",
    tocDialogAriaLabel: "Slide table of contents",
    tocTitle: "Slide Table of Contents",
    closeButtonLabel: "Close",
  },
  slideIdOrder: [
    "title",
    "agent-definition",
    "operating-model",
    "authority-ladder",
    "evidence-auditability",
    "enterprise-integration",
    "transfer-escalation",
    "value-metrics",
    "accountability",
    "production-gate",
  ],
  slideTitles: [
    "How to Turn AI Agents Into Governed Digital Products",
    "What Makes an Enterprise AI Agent?",
    "The Enterprise Agent Operating Model",
    "Authority Is a Ladder, Not a Toggle",
    "Evidence & Auditability",
    "Integration in the Real Enterprise",
    "Transfer & Escalation",
    "How to Measure Real Value",
    "Who Is Accountable?",
    "Production-Ready Agent Checklist",
  ],
} as const;
