import type { PBDSKineticSphereProps } from "./orbTypes";

/**
 * Named PBDS orb configurations. `magentaRight` is the approved /pbds-orb-embed baseline;
 * values are the behavioral baseline and must not be "corrected" from older experiments.
 */
export const orbPresets = {
  magentaRight: {
    radius: 290,
    skinStyle: "canonical-magenta",
    accentColor: "#FF2FAE",
    primaryDotColor: "#FF2FAE",
    interactionMode: "repel",
    interactionStrength: 1.25,
    autoRotateSpeed: 0.0012,
    cropPosition: "orb-right",
    plasmaNoiseIntensity: 1,
    stippleDensity: 8500,
    ambientLuminance: 0.38,
    glowingStrokeIntensity: 0.2,
    strokeMode: "crescent",
    strokeShadowOpacity: 0,
    strokeWidth: 0.5,
    bodyOpacity: 0,
    interactive: true,
  },
  greyLeft: {
    radius: 290,
    skinStyle: "custom",
    accentColor: "#E2E8F0",
    primaryDotColor: "#E2E8F0",
    interactionMode: "repel",
    interactionStrength: 1.25,
    autoRotateSpeed: 0.0012,
    cropPosition: "orb-left",
    plasmaNoiseIntensity: 1,
    stippleDensity: 8500,
    ambientLuminance: 0.38,
    glowingStrokeIntensity: 0.14,
    // Tight metallic rim: narrow bloom, cooler core, minimal inner wash (renderer defaults 28 / 0.85 / 0.35).
    glowSpread: 12,
    coreHotness: 0.55,
    innerWashIntensity: 0.08,
    strokeMode: "crescent",
    strokeShadowOpacity: 0,
    strokeWidth: 0.7,
    bodyOpacity: 0,
    interactive: true,
  },
} as const satisfies Record<string, PBDSKineticSphereProps>;

export type PBDSOrbPresetName = keyof typeof orbPresets;

/** Accepted template-lab appearance profiles; consumers own only placement and speed overrides. */
export const orbAppearanceProfiles = {
  magentaAtmosphere: {
    atmosphereMode: "field" as const,
    atmosphereWidth: 11,
    atmosphereFocus: 3.5,
    atmosphereIntensity: 0.48,
    innerGlowWidth: 8,
    innerGlowIntensity: 0.11,
    innerGlowColor: "#FF2FAE",
    innerGlowFocus: 5,
    ambientLuminance: 0.52,
    autoRotateSpeed: 0.00045,
    plasmaSpeed: 0.8,
    outerGlowColor: "#FF2FAE",
    midGlowColor: "#FF65C7",
    hotCoreColor: "#FFF7FC",
    solarFlareIntensity: 1.35,
    surfaceColorMode: "lit-gradient" as const,
    surfaceShadowColor: "#3A0B28",
    surfaceDarkColor: "#7E165A",
    surfaceMidColor: "#FF2FAE",
    surfaceLightColor: "#FF78CB",
    surfaceHotColor: "#FF8FD5",
    surfaceHotThreshold: 0.9,
  },
  greyAtmosphere: {
    atmosphereMode: "field" as const,
    atmosphereWidth: 10,
    atmosphereFocus: 3.5,
    atmosphereIntensity: 0.38,
    innerGlowWidth: 8,
    innerGlowIntensity: 0.09,
    innerGlowColor: "#C9D3DE",
    innerGlowFocus: 5,
    ambientLuminance: 0.48,
    autoRotateSpeed: 0.00035,
    plasmaSpeed: 0.8,
    outerGlowColor: "#94A3B8",
    midGlowColor: "#CBD5E1",
    hotCoreColor: "#F6F8FA",
    solarFlareIntensity: 1.25,
    surfaceColorMode: "lit-gradient" as const,
    surfaceShadowColor: "#1F2933",
    surfaceDarkColor: "#56616F",
    surfaceMidColor: "#AEB8C4",
    surfaceLightColor: "#DCE3EA",
    surfaceHotColor: "#F6F8FA",
    surfaceHotThreshold: 0.9,
  },
  magentaRim: {
    autoRotateSpeed: 0.0012,
    plasmaSpeed: 0.8,
    outerGlowColor: "#FF2FAE",
    midGlowColor: "#FF65C7",
    hotCoreColor: "#FFF7FC",
    solarFlareIntensity: 1.35,
  },
} as const satisfies Record<string, PBDSKineticSphereProps>;
