import type { SecureCarolinas2026Content, SecureCarolinas2026SlideMeta } from "./types";
import { secureCarolinas2026SlideOrder } from "./types";

const ACT_I = "ACT I - Shift in Attack Surface";
const ACT_II = "ACT II - A.G.E.N.T.S. Operating Model";
const ACT_III = "ACT III - Put a Real Agent Through the Model";
const ACT_IV = "ACT IV - The Production Readiness Gate";
const EXECUTION_ACCOUNTABILITY = "Execution can be delegated. Accountability cannot.";

const slide = (
  id: string,
  title: string,
  subtitle: string,
  act: SecureCarolinas2026SlideMeta["act"],
  actLabel: string,
): SecureCarolinas2026SlideMeta => ({ id, title, subtitle, act, actLabel });

export const secureCarolinas2026Copy = {
  acts: {
    act1: ACT_I,
    act2: ACT_II,
    act3: ACT_III,
    act4: ACT_IV,
  },
  slides: {
    title: {
      id: "title",
      label: "Slide 1",
      searchLabel: "Act 1, attack surface, enterprise AI entrypoint",
      act: "ACT_I",
      actLabel: ACT_I,
      title: "Is Your Enterprise Ready to Put AI Into Production?",
      subtitle: "When Agentic AI Becomes an Attack Surface",
      eyebrow: "Secure Carolinas 2026 // Keynote",
      headerAct: ACT_II,
      footerName: "Jim Markunas",
      footerRole: "Digital Product & Program Security Leader",
      footerLinkText: "greatestpmever.com",
      footerLinkHref: "https://greatestpmever.com",
      footerActLabel: "SHIFT IN ATTACK SURFACE",
      coreThesisLabel: "Core Thesis",
      coreThesisQuote:
        "The dangerous moment isn't when the model gets smarter. It's when we give it permission to do things.",
    },
    copilots: {
      id: "copilots",
      label: "Slide 2",
      searchLabel: "Act 1, attack surface, enterprise AI entrypoint",
      act: "ACT_I",
      actLabel: ACT_I,
      title: "Copilots Were an Info Problem",
      subtitle: "Traditional generative AI produced outputs for humans to evaluate.",
      headerBadge: "Paradigm 01",
      pipelineLabel: "Traditional Copilot Pipeline",
      pipelineStatus: "Gated Execution",
      steps: [
        { label: "User", sub: "Initiates Prompt", highlight: false },
        { label: "AI Model", sub: "Generates Draft", highlight: false },
        { label: "AI Output", sub: "Information Output", highlight: false },
        { label: "Human", sub: "Execution Boundary", highlight: true },
        { label: "Action", sub: "Manual Change", highlight: false },
      ],
      panelText:
        "In the copilot era, models acted purely as advisors. The output risk was naturally bounded because a human employee reviewed, verified, and committed every enterprise action.",
      callout: "The human remained the execution boundary.",
      calloutLead: "The human",
      examples: [
        { num: "01", title: "Summarize a document", tag: "Synthesizing internal reports and briefs" },
        { num: "02", title: "Draft an email", tag: "Drafting correspondence for user approval" },
        { num: "03", title: "Answer a question", tag: "Searching company documentation" },
        { num: "04", title: "Generate code", tag: "Assisting engineers in IDE autocompletion" },
        { num: "05", title: "Recommend next steps", tag: "Presenting support options to human agents" },
      ],
      examplesLabel: "Common Copilot Workloads",
      exampleBadge: "Human Evaluated",
    },
    agents: {
      id: "agents",
      label: "Slide 3",
      searchLabel: "Act 1, attack surface, enterprise AI entrypoint",
      act: "ACT_I",
      actLabel: ACT_I,
      title: "Agents Now Execute",
      subtitle: "Autonomous execution shifts the model from advisor to operator.",
      flow: [
        { label: "GOAL", highlight: false },
        { label: "TOOL", highlight: false },
        { label: "SYSTEM", highlight: false },
        { label: "AGENT", highlight: true },
        { label: "ACTION", highlight: false },
      ],
      capabilitiesLabel: "READ · WRITE · SEND · SPEND",
      capabilities: ["READ", "WRITE", "SEND", "SPEND"],
      calloutLead: "It became an operator.",
      callout: "The model didn’t just generate an output.",
    },
    attackSurface: {
      id: "attack-surface",
      label: "Slide 4",
      searchLabel: "Act 1, attack surface, enterprise AI entrypoint",
      act: "ACT_I",
      actLabel: ACT_I,
      title: "Business Process = Attack Surface",
      subtitle: "Security must extend beyond infrastructure controls into governed autonomous execution.",
      traditionalLabel: "Traditional Attack Surface",
      agenticLabel: "Agentic Attack Surface",
      plusLabel: "+",
      traditional: [
        { name: "Endpoints" },
        { name: "Networks" },
        { name: "Applications" },
        { name: "Identities" },
        { name: "APIs" },
      ],
      agentic: [
        { name: "Delegated Authority" },
        { name: "Connected Systems" },
        { name: "Untrusted Inputs" },
        { name: "Stored Context" },
        { name: "Autonomous Decisions" },
      ],
      coreTakeaway:
        "An agent can behave exactly as designed and still cause an incident if the operating model is wrong.",
    },
    question: {
      id: "question-before-production",
      label: "Slide 5",
      searchLabel: "Act 2, A.G.E.N.T.S. controls, readiness requirements",
      act: "ACT_II",
      actLabel: ACT_II,
      title: "The Question Before Production",
      subtitle: "What must be true before we allow an AI agent to act on behalf of the enterprise?",
      headerBadge: "Framework Launch",
      bannerLabel: "The Fundamental Production Gate",
      questionQuote:
        "What must be true before we allow an AI agent to act on behalf of the enterprise?",
      pillars: [
        { letter: "A", name: "Authority", desc: "What is the agent allowed to decide & do?" },
        { letter: "G", name: "Guardrails", desc: "Under what conditions may it act?" },
        { letter: "E", name: "Evidence", desc: "Can we reconstruct what occurred?" },
        { letter: "N", name: "Network & Integrations", desc: "What systems can it reach & affect?" },
        { letter: "T", name: "Transfer & Escalation", desc: "What happens when it must stop?" },
        { letter: "S", name: "Success & Accountability", desc: "Who owns the final outcome?" },
      ],
      framingLabel: "A.G.E.N.T.S. Standard",
      framing: "Governed Execution: This is not an AI ethics checklist. It is an enterprise operating model for governed autonomous execution.",
      framingEmphasis: "Governed Execution:",
    },
    authority: {
      id: "authority",
      label: "Slide 6",
      searchLabel: "Act 2, A.G.E.N.T.S. controls, readiness requirements",
      act: "ACT_II",
      actLabel: ACT_II,
      title: "A - Authority",
      subtitle: "What is this agent actually allowed to decide and do?",
      headerBadge: "Pillar 1 of 6",
      ladderLabel: "The Authority Ladder (Stepped Elevation)",
      ladderBadge: "Bounded Progression",
      ladder: [
        { level: "01", name: "Observe", desc: "Read-only context intake without mutation" },
        { level: "02", name: "Recommend", desc: "Advise human operator on optimal actions" },
        { level: "03", name: "Draft", desc: "Stage proposed mutations for human validation" },
        { level: "04", name: "Execute w/ Approval", desc: "Requires explicit human authorization" },
        { level: "05", name: "Execute within Limits", desc: "Autonomous within bounded policy gates" },
        { level: "06", name: "Escalate", desc: "Mandatory handover when limits are reached" },
      ],
      conceptsLabel: "Key Governance Mechanisms",
      concepts: [
        { title: "Bounded Autonomy", text: "Explicit scopes of allowable actions and functions" },
        { title: "Transaction Limits", text: "Hard financial caps (e.g., maximum refund $100)" },
        { title: "Approval Thresholds", text: "Triggers that require mandatory supervisor sign-off" },
        { title: "Prohibited Actions", text: "Immutable blacklist of forbidden system changes" },
        { title: "Revocation", text: "Instant kill-switch and privilege deprovisioning" },
      ],
      anchor: "Authority is a ladder, not a toggle.",
    },
    guardrails: {
      id: "guardrails",
      label: "Slide 7",
      searchLabel: "Act 2, A.G.E.N.T.S. controls, readiness requirements",
      act: "ACT_II",
      actLabel: ACT_II,
      title: "G - Guardrails",
      subtitle: "Under what conditions may the agent exercise that authority?",
      headerBadge: "Pillar 2 of 6",
      fragileLabel: "Fragile Assumption",
      fragileTitle: "Prompt Instruction",
      fragileBody:
        "Telling the LLM in natural language: “Please do not issue refunds over $100.” Vulnerable to prompt injections, hallucinations, and context loss.",
      controlLabel: "Architectural Control",
      controlTitle: "Deterministic System Enforcement",
      controlBody:
        "API gateway policies, rate limits, deterministic schemas, and cryptographically signed scopes that mechanically reject unauthorized requests.",
      enforcementsLabel: "Deterministic Guardrail Enforcements",
      guardrails: [
        { name: "Policy Constraints", desc: "Internal operational rules and customer guidelines" },
        { name: "Compliance Rules", desc: "SOX, HIPAA, GDPR, SOC2 statutory verifications" },
        { name: "Financial Thresholds", desc: "Deterministic caps on discounts, credits, refunds" },
        { name: "Confidence Thresholds", desc: "Minimum probabilistic score before execution" },
        { name: "Prohibited Actions", desc: "Immutable blacklist of restricted tool parameters" },
        { name: "Validation Requirements", desc: "Strict runtime JSON schema and type verification" },
        { name: "Customer Protections", desc: "Automated PII scrubbing, sentiment enforcement" },
      ],
      anchor: "If the consequence matters, the surrounding system should enforce the rule.",
      anchorBadge: "Prompt instruction ≠ Control",
    },
    evidence: {
      id: "evidence",
      label: "Slide 8",
      searchLabel: "Act 2, A.G.E.N.T.S. controls, readiness requirements",
      act: "ACT_II",
      actLabel: ACT_II,
      title: "E - Evidence",
      subtitle: "Can we reconstruct what happened?",
      headerBadge: "Pillar 3 of 6",
      timelineLabel: "Auditable Operational Timeline",
      questionsLabel: "What the Enterprise Must Be Able to Determine",
      pipeline: [
        { step: "Intent", desc: "Goal & prompt context" },
        { step: "Inputs", desc: "RAG & database context" },
        { step: "Decision", desc: "Selected action path" },
        { step: "Tool Calls", desc: "Payloads & parameters" },
        { step: "State Change", desc: "System mutation record" },
        { step: "Outcome", desc: "Verifiable business result" },
      ],
      questions: [
        "What the agent knew at decision time",
        "What strategy it decided to execute",
        "Which specific tools it called",
        "What human approvals occurred",
        "What enterprise state changed",
        "Whether the action succeeded",
        "Why the case escalated (if any)",
      ],
      anchor: "We're not asking for hidden model reasoning. We're asking for an auditable operational record.",
    },
    network: {
      id: "network-integrations",
      label: "Slide 9",
      searchLabel: "Act 2, A.G.E.N.T.S. controls, readiness requirements",
      act: "ACT_II",
      actLabel: ACT_II,
      title: "N - Network & Integrations",
      subtitle: "What can the agent reach - and therefore affect?",
      headerBadge: "Pillar 4 of 6",
      badPatternLabel: "Anti-Pattern (Catastrophic Blast Radius)",
      badPatternIntro: "Blanket / Broad Enterprise System Access",
      badPatterns: [
        { title: "Broad CRM Admin Access", tag: "Full read/write credentials" },
        { title: "Production DB Direct Access", tag: "Unconstrained SQL execution" },
        { title: "Full Mailbox Send/Receive", tag: "Unfiltered outbound communication" },
        { title: "Unrestricted Billing API", tag: "Global financial authority" },
      ],
      governedLabel: "Governed Pattern (Blast Radius Containment)",
      governedIntro: "Narrowly Defined, Purpose-Built Tool Endpoints",
      capabilities: [
        { name: "retrieve_order", scope: "Read-only Order Status" },
        { name: "issue_credit_under_$100", scope: "Scoped Finance Function" },
        { name: "create_support_ticket", scope: "Structured Case Creation" },
        { name: "schedule_shipment", scope: "Fulfillment Dispatch API" },
      ],
      anchor: "Give the agent capabilities, not blanket access.",
      anchorBadge: "Principle of Least Privilege",
    },
    transfer: {
      id: "transfer-escalation",
      label: "Slide 10",
      searchLabel: "Act 2, A.G.E.N.T.S. controls, readiness requirements",
      act: "ACT_II",
      actLabel: ACT_II,
      title: "T - Transfer & Escalation",
      subtitle: "What happens when the agent should stop?",
      headerBadge: "Pillar 5 of 6",
      badLabel: "Bad Escalation",
      badTitle: "Agent Fails → Sends Generic Alert → Human Starts from Zero",
      badBody: "Destroys employee productivity, increases MTTR, and degrades customer trust.",
      goodLabel: "Good Escalation",
      goodTitle: "Agent Stops → Packages Full Context → Human Continues Flow",
      goodBody: "Clean handover of state, telemetry, and synthesized next actions.",
      payloadLabel: "What the Human Inherits (The Handover Payload)",
      payload: [
        { label: "Objective", desc: "Original task assignment" },
        { label: "Customer Context", desc: "Tier, lifetime value, history" },
        { label: "Actions Attempted", desc: "Lookups, partial tool calls" },
        { label: "Evidence Gathered", desc: "Order snapshots & telemetry" },
        { label: "Current State", desc: "Exact status in OMS/CRM" },
        { label: "Reason for Escalation", desc: "Limit reached or ambiguity" },
        { label: "Recommended Action", desc: "Synthesized options for human" },
      ],
      anchor: "A human should inherit the work — not restart it.",
    },
    success: {
      id: "success-accountability",
      label: "Slide 11",
      searchLabel: "Act 2, A.G.E.N.T.S. controls, readiness requirements",
      act: "ACT_II",
      actLabel: ACT_II,
      title: "S - Success & Accountability",
      subtitle: "How do we know this agent should continue operating - and who owns the result?",
      headerBadge: "Pillar 6 of 6",
      coreLabel: "Core Principle:",
      coreText: "Success cannot simply mean: “The agent completed the task.”",
      taskBadge: "Task Completion ≠ Success",
      metricsLabel: "8 Dimensions of Agentic Operational Health",
      metrics: [
        { name: "Business Outcome", desc: "Dispute resolution time & satisfaction" },
        { name: "Accuracy", desc: "Correct rule application vs ground truth" },
        { name: "Error Rate", desc: "Failed API calls, erroneous state changes" },
        { name: "Unnecessary Actions", desc: "Superfluous tool calls and lookups" },
        { name: "Escalation Rate", desc: "Percentage of cases routed to humans" },
        { name: "Customer Impact", desc: "CSAT, repeat contacts, dispute scores" },
        { name: "Operational Cost", desc: "Token usage, API charges, triage labor" },
        { name: "Operational Risk", desc: "Policy near-misses and anomaly metrics" },
      ],
      ownershipLabel: "OWNERSHIP",
      ownershipText: "One person or function must ultimately own the agent.",
      anchor: EXECUTION_ACCOUNTABILITY,
    },
    meetAgent: {
      id: "meet-agent",
      label: "Slide 12",
      searchLabel: "Act 3, customer order exception agent, live decision board",
      act: "ACT_III",
      actLabel: ACT_III,
      title: "Meet the Agent: Customer Order Exception Agent",
      subtitle: "Scenario: An enterprise wants an autonomous AI agent to resolve eCommerce and fulfillment exceptions.",
      headerBadge: "Dossier & Scope",
      capabilitiesLabel: "Agent Tool Registry & Permissions",
      capabilitiesBadge: "Autonomous Exception Handler",
      capabilities: [
        { label: "Inspect Order", desc: "Read order line items, status, payment state" },
        { label: "Check Inventory", desc: "Query warehouse stocks, distribution ETAs" },
        { label: "Query CRM", desc: "Review customer profile, lifetime value" },
        { label: "Change Fulfillment", desc: "Reroute carrier package, split shipments" },
        { label: "Issue Credits", desc: "Trigger refunds or store loyalty credits" },
        { label: "Notify Customers", desc: "Dispatch automated transactional email/SMS" },
        { label: "Escalate Cases", desc: "Route anomalous disputes to tier-2 team" },
      ],
      introLabel: "Initial Enterprise Perception",
      introQuote: "A high-value, obvious use case for an agent.",
      introBody:
        "High volume, repetitive decisions, directly addresses customer wait times and support backlog.",
      governanceLabel: "The Governance Test",
      governanceQuote: "Is it actually ready for production?",
      governanceBody: "Let's evaluate this exact agent through all 6 pillars of the A.G.E.N.T.S. framework.",
    },
    decisionBoard: {
      id: "decision-board",
      label: "Slide 13",
      searchLabel: "Act 3, customer order exception agent, live decision board",
      act: "ACT_III",
      actLabel: ACT_III,
      title: "Live Decision Board: Customer Order Exception Agent",
      subtitle: "Applying the 6 pillars transforms ambiguous autonomy into bounded, auditable operations.",
      headerBadge: "Production Board",
      board: [
        { letter: "A", name: "Authority", rule: "May issue credits ≤ $100. Higher amounts require mandatory human supervisor approval.", badge: "Bounded Caps" },
        { letter: "G", name: "Guardrails", rule: "Cannot override fraud flags, regulated pricing tiers, or restricted SKU policies.", badge: "Hard Policies" },
        { letter: "E", name: "Evidence", rule: "Every customer lookup, decision path, API payload, approval, and DB change logged.", badge: "Full Telemetry" },
        { letter: "N", name: "Network & Integrations", rule: "Read OMS + inventory. Strictly limited write access to refund credits and case management.", badge: "Least Privilege" },
        { letter: "T", name: "Transfer & Escalation", rule: "Conflicting customer records or >$100 impact transfers with structured state & history.", badge: "Zero-Loss Handover" },
        { letter: "S", name: "Success & Accountability", rule: "Operations Lead owns the agent. Evaluated on resolution time, accuracy, and escalations.", badge: "Explicit Owner" },
      ],
      anchor: "Autonomy becomes manageable when the boundaries are explicit.",
      anchorBadge: "Operational Blueprint",
    },
    readinessStatus: {
      id: "readiness-status",
      label: "Slide 14",
      searchLabel: "Act 4, production readiness gate, executive decision",
      act: "ACT_IV",
      actLabel: ACT_IV,
      title: "Defined. Partial. Unclear.",
      subtitle: "Every A.G.E.N.T.S. domain receives an unambiguous readiness status.",
      statuses: [
        { label: "DEFINED", definition: "Explicit, implemented, understood, and owned.", implication: "Deterministic controls & automated test suites exist in production." },
        { label: "PARTIAL", definition: "Control exists, but material operational gaps remain.", implication: "Requires explicit mitigations & bounded customer rollout." },
        { label: "UNCLEAR", definition: "The organization cannot explain or demonstrate the control.", implication: "Immediate hard blocker for production deployment." },
      ],
      gateRules: [
        { cond: "Any UNCLEAR", outcome: "NO GO" },
        { cond: "No UNCLEAR + ≥1 PARTIAL", outcome: "GO WITH CONDITIONS" },
        { cond: "All 6 DEFINED", outcome: "GO" },
      ],
      anchor: "Uncertainty in an autonomous agent is not technical debt. It is an active operational risk.",
      anchorBadge: "Binary Governance",
    },
    productionDecision: {
      id: "production-decision",
      label: "Slide 15",
      searchLabel: "Act 4, production readiness gate, executive decision",
      act: "ACT_IV",
      actLabel: ACT_IV,
      title: "The Production Decision",
      subtitle: "If any A.G.E.N.T.S. control is unclear, the agent is not ready.",
      decisions: [
        { title: "GO", status: "Production Ready", desc: "All 6 A.G.E.N.T.S. controls defined, tested, and actively monitored.", badgeText: "6/6 Defined" },
        { title: "GO WITH CONDITIONS", status: "Constrained Rollout", desc: "Known limitations with explicit circuit breakers, low limits, and shadow audits.", badgeText: "Partial Allowed" },
        { title: "NO GO", status: "Hard Stop", desc: "At least one material control is unclear. Block production release immediately.", badgeText: "≥1 Unclear" },
      ],
      purposeLabel: "The Purpose of Governance",
      purposeQuote: "The goal isn't to stop autonomous AI. The goal is to know exactly where autonomy ends.",
      finalLabel: "Final Spoken Takeaway",
      finalQuote: EXECUTION_ACCOUNTABILITY,
    },
    closingCta: {
      id: "closing-cta",
      label: "Slide 16",
      searchLabel: "Act 4, production readiness gate, executive decision",
      act: "ACT_IV",
      actLabel: ACT_IV,
      title: "Put A.G.E.N.T.S. to Work.",
      subtitle: "Free enterprise AI operating model + production readiness check.",
      headerEyebrow: "Secure Carolinas 2026 · A.G.E.N.T.S. Closing CTA",
      actions: ["USE IT", "FORK IT", "CHALLENGE IT", "REPORT ADOPTION"],
      scanText: "Scan to use it, fork it, challenge it, or report adoption.",
      linkText: "greatestpmever.com/agents",
      linkHref: "https://greatestpmever.com/agents",
    },
  },
} as const;

const slides = secureCarolinas2026Copy.slides;

export const secureCarolinas2026Content: SecureCarolinas2026Content = {
  navigation: {
    previousAriaLabel: "Previous slide",
    nextAriaLabel: "Next slide",
    openTocAriaLabel: "Open slide table of contents",
    toggleFullscreenAriaLabel: "Toggle fullscreen",
    tocDialogAriaLabel: "Slide table of contents",
    tocTitle: "Slide Table of Contents",
    closeButtonLabel: "Close",
  },
  slideOrder: secureCarolinas2026SlideOrder,
  slides: {
    title: slide(slides.title.id, slides.title.title, slides.title.subtitle, slides.title.act, slides.title.actLabel),
    copilots: slide(slides.copilots.id, slides.copilots.title, slides.copilots.subtitle, slides.copilots.act, slides.copilots.actLabel),
    agents: slide(slides.agents.id, slides.agents.title, slides.agents.subtitle, slides.agents.act, slides.agents.actLabel),
    attackSurface: slide(slides.attackSurface.id, slides.attackSurface.title, slides.attackSurface.subtitle, slides.attackSurface.act, slides.attackSurface.actLabel),
    question: slide(slides.question.id, slides.question.title, slides.question.subtitle, slides.question.act, slides.question.actLabel),
    authority: slide(slides.authority.id, slides.authority.title, slides.authority.subtitle, slides.authority.act, slides.authority.actLabel),
    guardrails: slide(slides.guardrails.id, slides.guardrails.title, slides.guardrails.subtitle, slides.guardrails.act, slides.guardrails.actLabel),
    evidence: slide(slides.evidence.id, slides.evidence.title, slides.evidence.subtitle, slides.evidence.act, slides.evidence.actLabel),
    network: slide(slides.network.id, slides.network.title, slides.network.subtitle, slides.network.act, slides.network.actLabel),
    transfer: slide(slides.transfer.id, slides.transfer.title, slides.transfer.subtitle, slides.transfer.act, slides.transfer.actLabel),
    success: slide(slides.success.id, slides.success.title, slides.success.subtitle, slides.success.act, slides.success.actLabel),
    meetAgent: slide(slides.meetAgent.id, slides.meetAgent.title, slides.meetAgent.subtitle, slides.meetAgent.act, slides.meetAgent.actLabel),
    decisionBoard: slide(slides.decisionBoard.id, slides.decisionBoard.title, slides.decisionBoard.subtitle, slides.decisionBoard.act, slides.decisionBoard.actLabel),
    readinessStatus: slide(slides.readinessStatus.id, slides.readinessStatus.title, slides.readinessStatus.subtitle, slides.readinessStatus.act, slides.readinessStatus.actLabel),
    productionDecision: slide(slides.productionDecision.id, slides.productionDecision.title, slides.productionDecision.subtitle, slides.productionDecision.act, slides.productionDecision.actLabel),
    closingCta: slide(slides.closingCta.id, slides.closingCta.title, slides.closingCta.subtitle, slides.closingCta.act, slides.closingCta.actLabel),
  },
};
