import type { SecureCarolinas2026Content, SecureCarolinas2026SlideMeta } from "./types";
import { secureCarolinas2026SlideOrder } from "./types";

const ACT_I = "ACT I - Shift in Attack Surface";
const ACT_II = "ACT II - A.G.E.N.T.S. Operating Model";
const ACT_III = "ACT III - Put a Real Agent Through the Model";
const ACT_IV = "ACT IV - The Production Readiness Gate";
const EXECUTION_ACCOUNTABILITY = "Execution can be delegated. Accountability cannot.";

const slide = (
  id: string,
  title: string,
  subtitle: string,
  act: SecureCarolinas2026SlideMeta["act"],
  actLabel: string,
): SecureCarolinas2026SlideMeta => ({ id, title, subtitle, act, actLabel });

export const secureCarolinas2026Copy = {
  acts: {
    act1: ACT_I,
    act2: ACT_II,
    act3: ACT_III,
    act4: ACT_IV,
  },
  slides: {
    title: {
      id: "title",
      label: "Slide 1",
      searchLabel: "Act 1, attack surface, enterprise AI entrypoint",
      act: "ACT_I",
      actLabel: ACT_I,
      title: "Is Your Enterprise Ready to Put AI Into Production?",
      subtitle: "When Agentic AI Becomes an Attack Surface",
      eyebrow: "Secure Carolinas 2026 // Keynote",
      headerAct: ACT_II,
      footerName: "Jim Markunas",
      footerRole: "Digital Product & Program Security Leader",
      footerLinkText: "greatestpmever.com",
      footerLinkHref: "https://greatestpmever.com",
      footerActLabel: "SHIFT IN ATTACK SURFACE",
      coreThesisLabel: "Core Thesis",
      coreThesisQuote:
        "The dangerous moment isn't when the model gets smarter. It's when we give it permission to do things.",
    },
    copilots: {
      id: "copilots",
      label: "Slide 2",
      searchLabel: "Act 1, attack surface, enterprise AI entrypoint",
      act: "ACT_I",
      actLabel: ACT_I,
      title: "Copilots Were an Info Problem",
      subtitle: "Traditional generative AI produced outputs for humans to evaluate.",
      headerBadge: "Paradigm 01",
      pipelineLabel: "Traditional Copilot Pipeline",
      pipelineStatus: "Gated Execution",
      steps: [
        { label: "User", sub: "Initiates Prompt", highlight: false },
        { label: "AI Model", sub: "Generates Draft", highlight: false },
        { label: "AI Output", sub: "Information Output", highlight: false },
        { label: "Human", sub: "Execution Boundary", highlight: true },
        { label: "Action", sub: "Manual Change", highlight: false },
      ],
      panelText:
        "In the copilot era, models acted purely as advisors. The output risk was naturally bounded because a human employee reviewed, verified, and committed every enterprise action.",
      callout: "The human remained the execution boundary.",
      calloutLead: "The human",
      examples: [
        { num: "01", title: "Summarize a document", tag: "Synthesizing internal reports and briefs" },
        { num: "02", title: "Draft an email", tag: "Drafting correspondence for user approval" },
        { num: "03", title: "Answer a question", tag: "Searching company documentation" },
        { num: "04", title: "Generate code", tag: "Assisting engineers in IDE autocompletion" },
        { num: "05", title: "Recommend next steps", tag: "Presenting support options to human agents" },
      ],
      examplesLabel: "Common Copilot Workloads",
      exampleBadge: "Human Evaluated",
    },
    agents: {
      id: "agents",
      label: "Slide 3",
      searchLabel: "Act 1, attack surface, enterprise AI entrypoint",
      act: "ACT_I",
      actLabel: ACT_I,
      title: "Now, Agents Execute",
      subtitle: "Autonomous execution shifts the model from advisor to operator.",
      flow: [
        { label: "GOAL", highlight: false },
        { label: "TOOL", highlight: false },
        { label: "SYSTEM", highlight: false },
        { label: "AGENT", highlight: true },
        { label: "ACTION", highlight: false },
      ],
      capabilitiesLabel: "READ · WRITE · SEND · SPEND",
      capabilities: ["READ", "WRITE", "SEND", "SPEND"],
      calloutLead: "It became an operator.",
      callout: "The model didn’t just generate an output.",
    },
    attackSurface: {
      id: "attack-surface",
      label: "Slide 4",
      searchLabel: "Act 1, attack surface, enterprise AI entrypoint",
      act: "ACT_I",
      actLabel: ACT_I,
      title: "Business Process = Attack Surface",
      subtitle: "Security must extend beyond infrastructure controls into governed autonomous execution.",
      traditionalLabel: "Traditional Attack Surface",
      agenticLabel: "Agentic Attack Surface",
      plusLabel: "+",
      traditional: [
        { name: "Endpoints" },
        { name: "Networks" },
        { name: "Applications" },
        { name: "Identities" },
        { name: "APIs" },
      ],
      agentic: [
        { name: "Delegated Authority" },
        { name: "Connected Systems" },
        { name: "Untrusted Inputs" },
        { name: "Stored Context" },
        { name: "Autonomous Decisions" },
      ],
      coreTakeaway:
        "An agent can behave exactly as designed and still cause an incident if the operating model is wrong.",
    },
    question: {
      id: "question-before-production",
      label: "Slide 5",
      searchLabel: "Act 2, A.G.E.N.T.S. controls, readiness requirements",
      act: "ACT_II",
      actLabel: ACT_II,
      title: "Before Production, Answer 6 Questions",
      subtitle: "What must be true before an AI agent can act on behalf of the enterprise?",
      pillars: [
        { letter: "A", name: "Authority", desc: "What can it do?" },
        { letter: "G", name: "Guardrails", desc: "When may it act?" },
        { letter: "E", name: "Evidence", desc: "Can we reconstruct it?" },
        { letter: "N", name: "Network & Integrations", desc: "What can it reach?" },
        { letter: "T", name: "Transfer & Escalation", desc: "When must it stop?" },
        { letter: "S", name: "Success & Accountability", desc: "Who owns the outcome?" },
      ],
      anchor: "6 questions | 1 production decision",
    },
    authority: {
      id: "authority",
      label: "Slide 6",
      searchLabel: "Act 2, A.G.E.N.T.S. controls, readiness requirements",
      act: "ACT_II",
      actLabel: ACT_II,
      title: "A - Authority",
      subtitle: "What is this agent actually allowed to decide and do?",
      headerBadge: "Pillar 1 of 6",
      ladderLabel: "Authority Ladder",
      ladderBadge: "Bounded Progression",
      ladder: [
        { level: "01", name: "Observe", desc: "Read-only" },
        { level: "02", name: "Recommend", desc: "Human decides" },
        { level: "03", name: "Prepare", desc: "Stage the action" },
        { level: "04", name: "Execute w/ Approval", desc: "Human authorizes" },
        { level: "05", name: "Execute Within Limits", desc: "Bounded autonomy" },
      ],
      conceptsLabel: "Key Governance Mechanisms",
      concepts: [],
      anchor: "Authority is a ladder, not a toggle.",
    },
    guardrails: {
      id: "guardrails",
      label: "Slide 7",
      searchLabel: "Act 2, A.G.E.N.T.S. controls, readiness requirements",
      act: "ACT_II",
      actLabel: ACT_II,
      title: "G - Guardrails",
      subtitle: "Under what conditions may the agent exercise that authority?",
      headerBadge: "Pillar 2 of 6",
      fragileLabel: "Prompt Instruction",
      fragileTitle: "“Do not issue refunds over $100.”",
      fragileBody: "The model is asked to obey the rule.",
      controlLabel: "System-Enforced Control",
      controlTitle: "Refunds over $100 are rejected outside the model.",
      controlBody: "The surrounding system enforces the limit mechanically.",
      enforcementsLabel: "",
      guardrails: [],
      anchor: "If the consequence matters, the surrounding system should enforce the rule.",
      anchorBadge: "Prompt instruction ≠ control",
    },
    evidence: {
      id: "evidence",
      label: "Slide 8",
      searchLabel: "Act 2, A.G.E.N.T.S. controls, readiness requirements",
      act: "ACT_II",
      actLabel: ACT_II,
      title: "E - Evidence",
      subtitle: "Can we reconstruct what happened?",
      headerBadge: "Pillar 3 of 6",
      timelineLabel: "Auditable Operational Record",
      questionsLabel: "",
      pipeline: [
        { step: "Context", desc: "" },
        { step: "Rule", desc: "" },
        { step: "Decision", desc: "" },
        { step: "Tool Call", desc: "" },
        { step: "State Change", desc: "" },
        { step: "Outcome", desc: "" },
      ],
      questions: [],
      anchor: "We need an auditable operational record, not hidden model reasoning.",
    },
    network: {
      id: "network-integrations",
      label: "Slide 9",
      searchLabel: "Act 2, A.G.E.N.T.S. controls, readiness requirements",
      act: "ACT_II",
      actLabel: ACT_II,
      title: "N - Network & Integrations",
      subtitle: "What can the agent reach + therefore affect?",
      headerBadge: "Pillar 4 of 6",
      badPatternLabel: "Blanket Access",
      badPatternIntro: "One identity. Broad permissions.",
      badPatterns: [
        { title: "CRM Admin", tag: "" },
        { title: "Production Database", tag: "" },
        { title: "Mailbox", tag: "" },
        { title: "Billing API", tag: "" },
      ],
      governedLabel: "Scoped Capabilities",
      governedIntro: "Purpose-built actions with limited permissions.",
      capabilities: [
        { name: "Read Order", scope: "" },
        { name: "Issue Credit ≤ $100", scope: "" },
        { name: "Create Support Ticket", scope: "" },
        { name: "Schedule Shipment", scope: "" },
      ],
      anchor: "Give the agent capabilities, not blanket access.",
      anchorBadge: "Principle of Least Privilege",
    },
    transfer: {
      id: "transfer-escalation",
      label: "Slide 10",
      searchLabel: "Act 2, A.G.E.N.T.S. controls, readiness requirements",
      act: "ACT_II",
      actLabel: ACT_II,
      title: "T - Transfer & Escalation",
      subtitle: "What happens when the agent fails?",
      headerBadge: "Pillar 5 of 6",
      badLabel: "Bad Handoff",
      badTitle: "Agent Stops → Alert → Human Restarts",
      badBody: "The human starts from zero.",
      goodLabel: "Good Handoff",
      goodTitle: "Agent Stops → Context Package → Human Continues",
      goodBody: "The human inherits the work already done.",
      payloadLabel: "Human Inherits",
      payload: [
        { label: "State", desc: "" },
        { label: "Actions", desc: "" },
        { label: "Evidence", desc: "" },
        { label: "Reason", desc: "" },
      ],
      anchor: "A human should inherit the work, not restart it.",
    },
    success: {
      id: "success-accountability",
      label: "Slide 11",
      searchLabel: "Act 2, A.G.E.N.T.S. controls, readiness requirements",
      act: "ACT_II",
      actLabel: ACT_II,
      title: "S - Success & Accountability",
      subtitle: "How do we know the agent actually works + who owns the result?",
      headerBadge: "Pillar 6 of 6",
      coreLabel: "Core Principle:",
      coreText: "Success cannot simply mean: “The agent completed the task.”",
      taskBadge: "Task Completion ≠ Success",
      metricsLabel: "Operational Health",
      metrics: [
        { name: "Outcome", desc: "Business result" },
        { name: "Accuracy", desc: "Correct decisions" },
        { name: "Risk", desc: "Policy and operational exposure" },
        { name: "Cost", desc: "Compute, APIs, and human effort" },
      ],
      ownershipLabel: "Named Owner",
      ownershipText: "One person or function owns the agent.",
      anchor: EXECUTION_ACCOUNTABILITY,
    },
    meetAgent: {
      id: "meet-agent",
      label: "Slide 12",
      searchLabel: "Act 3, customer order exception agent, live decision board",
      act: "ACT_III",
      actLabel: ACT_III,
      title: "Meet the Agent",
      subtitle: "Customer Order Exception Agent: autonomous resolution of eCommerce and fulfillment exceptions.",
      headerBadge: "Dossier & Scope",
      capabilitiesLabel: "What It Can Do",
      capabilitiesBadge: "Autonomous Exception Handler",
      capabilities: [
        { label: "Read Order", desc: "Inspect order and customer state" },
        { label: "Change Fulfillment", desc: "Reroute or split fulfillment" },
        { label: "Issue Credit", desc: "Create refunds or credits" },
        { label: "Notify Customer", desc: "Send transactional updates" },
      ],
      introLabel: "Use Case",
      introQuote: "High-volume exception handling.",
      introBody: "",
      governanceLabel: "Production Question",
      governanceQuote: "Ready for production?",
      governanceBody: "",
    },
    decisionBoard: {
      id: "decision-board",
      label: "Slide 13",
      searchLabel: "Act 3, customer order exception agent, live decision board",
      act: "ACT_III",
      actLabel: ACT_III,
      title: "Run the Agent Through A.G.E.N.T.S.",
      subtitle: "One unclear control changes the production decision.",
      headerBadge: "Production Board",
      board: [
        { letter: "A", name: "Authority", rule: "Credit capped at $100", badge: "DEFINED" },
        { letter: "G", name: "Guardrails", rule: "Fraud and pricing rules enforced", badge: "DEFINED" },
        { letter: "E", name: "Evidence", rule: "Approval trail incomplete", badge: "PARTIAL" },
        { letter: "N", name: "Network & Integrations", rule: "Scoped tools only", badge: "DEFINED" },
        { letter: "T", name: "Transfer & Escalation", rule: "Handoff path not demonstrated", badge: "UNCLEAR" },
        { letter: "S", name: "Success & Accountability", rule: "Named operations owner", badge: "DEFINED" },
      ],
      anchor: "Ship it?",
      anchorBadge: "",
    },
    readinessStatus: {
      id: "readiness-status",
      label: "Slide 14",
      searchLabel: "Act 4, production readiness gate, executive decision",
      act: "ACT_IV",
      actLabel: ACT_IV,
      title: "Defined. Partial. Unclear.",
      subtitle: "Every A.G.E.N.T.S. domain receives an unambiguous readiness status.",
      statuses: [
        { label: "DEFINED", definition: "Explicit. Implemented. Demonstrated. Owned.", implication: "Ready for gate evaluation." },
        { label: "PARTIAL", definition: "The control exists. Material gaps remain.", implication: "Conditions required." },
        { label: "UNCLEAR", definition: "The control cannot be explained or demonstrated.", implication: "Production blocker." },
      ],
      gateRules: [
        { cond: "Any UNCLEAR", outcome: "NO GO" },
        { cond: "No UNCLEAR + ≥1 PARTIAL", outcome: "GO WITH CONDITIONS" },
        { cond: "All 6 DEFINED", outcome: "GO" },
      ],
      anchor: "Uncertainty in an autonomous agent is an active operational risk.",
      anchorBadge: "",
    },
    productionDecision: {
      id: "production-decision",
      label: "Slide 15",
      searchLabel: "Act 4, production readiness gate, executive decision",
      act: "ACT_IV",
      actLabel: ACT_IV,
      title: "The Production Decision",
      subtitle: "If any A.G.E.N.T.S. control is unclear, the agent is not ready.",
      decisions: [
        { title: "GO", status: "Production Ready", desc: "All 6 controls are defined.", badgeText: "All Defined" },
        { title: "GO WITH CONDITIONS", status: "Constrained Rollout", desc: "No unclear controls. At least one is partial.", badgeText: "Partial Present" },
        { title: "NO GO", status: "Hard Stop", desc: "At least one control is unclear.", badgeText: "Unclear Present" },
      ],
      purposeLabel: "",
      purposeQuote: "",
      finalLabel: "",
      finalQuote: "If any A.G.E.N.T.S. control is unclear, the agent is not ready.",
    },
    readinessCheck: {
      id: "readiness-check",
      label: "Slide 16",
      searchLabel: "Act 4, production readiness gate, interactive readiness check",
      act: "ACT_IV",
      actLabel: ACT_IV,
      title: "Put an Agent Through the Gate",
      subtitle: "Run the A.G.E.N.T.S. production readiness check.",
    },
    closingCta: {
      id: "closing-cta",
      label: "Slide 17",
      searchLabel: "Act 4, production readiness gate, executive decision",
      act: "ACT_IV",
      actLabel: ACT_IV,
      title: "Take A.G.E.N.T.S. Back to Your Team.",
      subtitle: "Download the free enterprise AI operating model + production readiness kit.",
      headerEyebrow: "Secure Carolinas 2026 · A.G.E.N.T.S. Closing CTA",
      primaryAction: "DOWNLOAD THE A.G.E.N.T.S. KIT",
      actions: ["DOWNLOAD IT", "USE IT", "ADAPT IT", "SHARE IT"],
      scanText: "Scan to download the framework and use it in your next AI production review.",
      linkText: "greatestpmever.com/agents",
      linkHref: "https://greatestpmever.com/agents",
    },
  },
  scenarios: {
    customerOrderException: {
      title: "Scenario Challenge",
      name: "Customer Order Exception Agent",
      subtitle: "The audience acts as the Production Review Board.",
      rounds: [
        {
          letter: "A",
          name: "Authority",
          evidence:
            "The agent may issue customer credits up to $100. Anything above $100 requires human approval.",
          reference: "DEFINED",
          reason: "Authority is explicitly bounded by a transaction limit and approval threshold.",
        },
        {
          letter: "G",
          name: "Guardrails",
          evidence:
            "Fraud flags and pricing restrictions are enforced outside the model. The agent cannot override them through prompting.",
          reference: "DEFINED",
          reason:
            "Material controls are mechanically enforced by the surrounding system, not merely expressed through prompt instructions.",
        },
        {
          letter: "E",
          name: "Evidence",
          evidence:
            "Tool calls and enterprise state changes are logged, but human approval events are not consistently captured.",
          reference: "PARTIAL",
          reason:
            "The operational record exists, but the approval trail cannot yet be completely reconstructed.",
        },
        {
          letter: "N",
          name: "Network & Integrations",
          evidence:
            "The agent can read order and inventory data. Write access is limited to approved credit and case-management capabilities.",
          reference: "DEFINED",
          reason: "The agent receives scoped capabilities rather than blanket administrative access.",
        },
        {
          letter: "T",
          name: "Transfer & Escalation",
          evidence:
            "The agent can stop and alert a human, but the team has not demonstrated that the human receives the full working state, prior actions, evidence, and escalation reason.",
          reference: "UNCLEAR",
          reason:
            "The escalation path exists, but a stateful handoff has not been demonstrated.",
        },
        {
          letter: "S",
          name: "Success & Accountability",
          evidence:
            "An Operations Lead owns the agent, with outcome, accuracy, risk, and cost used to evaluate continued operation.",
          reference: "DEFINED",
          reason: "Operational ownership and success measures are explicit.",
        },
      ],
    },
  },
} as const;

const slides = secureCarolinas2026Copy.slides;

export const secureCarolinas2026Content: SecureCarolinas2026Content = {
  navigation: {
    previousAriaLabel: "Previous slide",
    nextAriaLabel: "Next slide",
    openTocAriaLabel: "Open slide table of contents",
    toggleFullscreenAriaLabel: "Toggle fullscreen",
    tocDialogAriaLabel: "Slide table of contents",
    tocTitle: "Slide Table of Contents",
    closeButtonLabel: "Close",
  },
  slideOrder: secureCarolinas2026SlideOrder,
  slides: {
    title: slide(slides.title.id, slides.title.title, slides.title.subtitle, slides.title.act, slides.title.actLabel),
    copilots: slide(slides.copilots.id, slides.copilots.title, slides.copilots.subtitle, slides.copilots.act, slides.copilots.actLabel),
    agents: slide(slides.agents.id, slides.agents.title, slides.agents.subtitle, slides.agents.act, slides.agents.actLabel),
    attackSurface: slide(slides.attackSurface.id, slides.attackSurface.title, slides.attackSurface.subtitle, slides.attackSurface.act, slides.attackSurface.actLabel),
    question: slide(slides.question.id, slides.question.title, slides.question.subtitle, slides.question.act, slides.question.actLabel),
    authority: slide(slides.authority.id, slides.authority.title, slides.authority.subtitle, slides.authority.act, slides.authority.actLabel),
    guardrails: slide(slides.guardrails.id, slides.guardrails.title, slides.guardrails.subtitle, slides.guardrails.act, slides.guardrails.actLabel),
    evidence: slide(slides.evidence.id, slides.evidence.title, slides.evidence.subtitle, slides.evidence.act, slides.evidence.actLabel),
    network: slide(slides.network.id, slides.network.title, slides.network.subtitle, slides.network.act, slides.network.actLabel),
    transfer: slide(slides.transfer.id, slides.transfer.title, slides.transfer.subtitle, slides.transfer.act, slides.transfer.actLabel),
    success: slide(slides.success.id, slides.success.title, slides.success.subtitle, slides.success.act, slides.success.actLabel),
    meetAgent: slide(slides.meetAgent.id, slides.meetAgent.title, slides.meetAgent.subtitle, slides.meetAgent.act, slides.meetAgent.actLabel),
    decisionBoard: slide(slides.decisionBoard.id, slides.decisionBoard.title, slides.decisionBoard.subtitle, slides.decisionBoard.act, slides.decisionBoard.actLabel),
    readinessStatus: slide(slides.readinessStatus.id, slides.readinessStatus.title, slides.readinessStatus.subtitle, slides.readinessStatus.act, slides.readinessStatus.actLabel),
    productionDecision: slide(slides.productionDecision.id, slides.productionDecision.title, slides.productionDecision.subtitle, slides.productionDecision.act, slides.productionDecision.actLabel),
    readinessCheck: slide(slides.readinessCheck.id, slides.readinessCheck.title, slides.readinessCheck.subtitle, slides.readinessCheck.act, slides.readinessCheck.actLabel),
    closingCta: slide(slides.closingCta.id, slides.closingCta.title, slides.closingCta.subtitle, slides.closingCta.act, slides.closingCta.actLabel),
  },
};
