export const agentsContent = {
  meta: {
    title: "A.G.E.N.T.S. Enterprise AI Operating Model | Jim Markunas",
    description:
      "A.G.E.N.T.S. is Jim Markunas’ enterprise AI agent operating model for defining authority, guardrails, evidence, integrations, escalation, business value, and accountability.",
  },
  hero: {
    title: "Want to ACTUALLY Get ROI Out of Agentic AI?",
    badge: "FREE system download + readiness preview",
    subhead: "Here’s how, in one complete enterprise system.",
    body: "A.G.E.N.T.S. is a complete enterprise AI operating model you can download, apply, star, fork, and report adoption against. The readiness check is a preview. The implementation package is the system.",
    primaryCta: "Get the free toolkit on GitHub",
    secondaryCta: "Star on GitHub",
    tertiaryCta: "Report adoption",
  },
  readiness: {
    heading: "Is your enterprise ready to put AI into production?",
    steps: ["Answer 9 questions", "Find the gaps", "Get a production decision", "Put AI into production"],
  },
  framework: {
    label: "What is A.G.E.N.T.S.?",
    heading: "A complete operating model for enterprise AI.",
    body: "A.G.E.N.T.S. is the system for turning enterprise AI from experimentation into measurable business capability. It gives your organization a practical way to define what AI may do, what must constrain it, what evidence it leaves, what systems it may touch, when people take over, and how the enterprise proves value.",
    controls: [
      ["A", "Authority", "What may AI do?", "Grant authority action by action."],
      ["G", "Guardrails", "What must constrain it?", "Set limits, approvals, prohibited actions, and hard stops."],
      ["E", "Evidence", "How will we know what it did?", "Preserve enough evidence to reconstruct every consequential action."],
      ["N", "Network and Integrations", "What systems may AI touch?", "Scope its systems, identities, data, and permissions."],
      ["T", "Transfer and Escalation", "When does a person take over?", "Define the handoff, transferred context, and resume conditions."],
      ["S", "Success and Accountability", "Did it create value, and who owns the result?", "Measure the result. Name the human accountable for it."],
    ],
  },
  productionGate: {
    label: "Production Gate",
    heading: "Before enterprise AI goes live, four things must be clear.",
    rows: [["01", "Value", "What business result should improve?"], ["02", "Authority", "What is AI allowed to do?"], ["03", "Evidence", "Can the enterprise reconstruct what happened?"], ["04", "Ownership", "Who owns the outcome?"]],
  },
  resources: {
    label: "Free System",
    heading: "Download the complete A.G.E.N.T.S. enterprise toolkit.",
    body: "Use the free toolkit to move from AI ambition to enterprise production readiness. Define the business case, map authority and access, set guardrails, document evidence, plan escalation, assign ownership, and run the gate before production.",
    items: ["Define the enterprise business case.", "Map authority, access, and system boundaries.", "Set guardrails and evidence requirements.", "Plan escalation and accountable ownership.", "Run the production readiness gate.", "Scale the model across the enterprise."],
    downloadCta: "Get the free toolkit on GitHub",
    openCta: "Open resource",
    githubHeading: "Use it, star it, report adoption.",
    githubBody:
      "The public GitHub repo is the home for the A.G.E.N.T.S. system. Star it if it is useful, fork it if you adapt it, and open an adoption report if your team uses it in a workshop, governance review, product planning session, or production readiness process. The free toolkit includes the PDF, editable DOCX, and Inter font package.",
    githubDownloadCta: "Get the free toolkit on GitHub",
    githubStarCta: "Star on GitHub",
    githubAdoptionCta: "Report adoption",
    githubDiscussionCta: "Join the discussion",
  },
  questions: [
    ["A", "Authority", "What may the agent do?", "Define its authority action by action: observe, recommend, prepare, decide, and execute."],
    ["G", "Guardrails", "What must constrain it?", "Define the policies, approvals, limits, prohibited actions, and hard stops that bound its authority."],
    ["E", "Evidence", "How will we know what it did?", "Preserve enough operational evidence to reconstruct consequential decisions and actions."],
    ["N", "Network & Integrations", "What systems may it touch?", "Define the systems, APIs, identities, data, permissions, and capabilities the agent may use."],
    ["T", "Transfer & Escalation", "When does a person take over?", "Define when the agent must stop, where the work goes, what context transfers, and whether the agent may resume."],
    ["S", "Success & Accountability", "Did it create value — and who owns the result?", "Measure the business outcome and identify the human owner accountable for that outcome."],
  ],
  stages: [
    ["FIND", "Identify the business opportunity, current process, relevant systems, friction, and potential value."],
    ["DEFINE", "Define the agent’s objective, information needs, decisions, actions, systems, and expected outcome."],
    ["GOVERN", "Apply the six A.G.E.N.T.S. controls before consequential authority is delegated."],
    ["PROVE", "Measure whether the agent produced the business result it was designed to improve."],
  ],
  authority: ["OBSERVE", "RECOMMEND", "PREPARE", "DECIDE", "EXECUTE"],
  evidence: ["SOURCE", "STATE", "CONSTRAINT", "DECISION", "ACTION", "OVERRIDE", "OUTCOME"],
  rules: [
    ["Refund ≤ $50", "May execute"],
    ["Refund > $50", "Prepare for human approval"],
    ["Payment already reversed", "Never refund again"],
    ["Conflicting payment state", "Stop and escalate"],
  ],
  valueCategories: ["Increase ROI / Revenue", "Decrease Cost", "Operational Efficiency / Streamlining"],
  finalQuestions: [
    "A — What may it do?",
    "G — What must constrain it?",
    "E — How will we know what it did?",
    "N — What systems may it touch?",
    "T — When does a person take over?",
    "S — Did it create value, and who owns the result?",
  ],
} as const
