import type { Slide5LayoutPreset } from "./slide5Diagram.types";

const CONNECTOR_STROKE = "#A3A3A3";
const CONNECTOR_STROKE_WIDTH = 1;

export const slide5DesktopLayoutPreset: Slide5LayoutPreset = {
  id: "desktop",
  canvas: {
    width: 1230,
    height: 566,
  },
  zones: [
    {
      id: "planning",
      x: 9,
      y: 55,
      w: 176,
      h: 464,
      labelKey: "planning",
      labelHeight: 44,
    },
    {
      id: "execution",
      x: 362,
      y: 55,
      w: 505,
      h: 320,
      labelKey: "execution",
      labelHeight: 44,
      border: {
        style: "dashed",
        width: 1,
        color: "#A3A3A3",
        radius: 0,
      },
    },
    {
      id: "delivery",
      x: 1036,
      y: 55,
      w: 176,
      h: 223,
      labelKey: "delivery",
      labelHeight: 44,
    },
  ],
  nodes: [
    {
      id: "planning-discovery",
      x: 19,
      y: 123,
      w: 160,
      h: 48,
      theme: "waterfall",
      labelKey: "planningDiscovery",
      radius: 8,
    },
    {
      id: "planning-jira",
      x: 19,
      y: 210,
      w: 160,
      h: 48,
      theme: "agile",
      labelKey: "planningJira",
      radius: 8,
    },
    {
      id: "planning-schedule",
      x: 19,
      y: 297,
      w: 160,
      h: 48,
      theme: "waterfall",
      labelKey: "planningSchedule",
      radius: 8,
    },
    {
      id: "planning-review",
      x: 19,
      y: 384,
      w: 160,
      h: 48,
      theme: "waterfall",
      labelKey: "planningReview",
      radius: 8,
    },
    {
      id: "planning-kickoff",
      x: 19,
      y: 471,
      w: 160,
      h: 48,
      theme: "waterfall",
      labelKey: "planningKickoff",
      radius: 8,
    },
    {
      id: "execution-grooming",
      x: 392,
      y: 133,
      w: 160,
      h: 48,
      theme: "agile",
      labelKey: "executionGrooming",
      radius: 8,
    },
    {
      id: "execution-versioning",
      x: 682,
      y: 133,
      w: 160,
      h: 48,
      theme: "waterfall",
      labelKey: "executionVersioning",
      radius: 8,
    },
    {
      id: "execution-standups",
      x: 392,
      y: 284,
      w: 160,
      h: 48,
      theme: "agile",
      labelKey: "executionStandups",
      radius: 8,
    },
    {
      id: "execution-sprint",
      x: 682,
      y: 284,
      w: 160,
      h: 48,
      theme: "agile",
      labelKey: "executionSprint",
      radius: 8,
    },
    {
      id: "delivery-qa",
      x: 1046,
      y: 133,
      w: 160,
      h: 48,
      theme: "waterfall",
      labelKey: "deliveryQa",
      radius: 8,
    },
    {
      id: "delivery-release",
      x: 1046,
      y: 230,
      w: 160,
      h: 48,
      theme: "waterfall",
      labelKey: "deliveryRelease",
      radius: 8,
    },
  ],
  connectors: [
    {
      id: "planning-1",
      from: { nodeId: "planning-discovery", side: "bottom" },
      to: { nodeId: "planning-jira", side: "top" },
      mode: "straight",
      stroke: CONNECTOR_STROKE,
      strokeWidth: CONNECTOR_STROKE_WIDTH,
    },
    {
      id: "planning-2",
      from: { nodeId: "planning-jira", side: "bottom" },
      to: { nodeId: "planning-schedule", side: "top" },
      mode: "straight",
      stroke: CONNECTOR_STROKE,
      strokeWidth: CONNECTOR_STROKE_WIDTH,
    },
    {
      id: "planning-3",
      from: { nodeId: "planning-schedule", side: "bottom" },
      to: { nodeId: "planning-review", side: "top" },
      mode: "straight",
      stroke: CONNECTOR_STROKE,
      strokeWidth: CONNECTOR_STROKE_WIDTH,
    },
    {
      id: "planning-4",
      from: { nodeId: "planning-review", side: "bottom" },
      to: { nodeId: "planning-kickoff", side: "top" },
      mode: "straight",
      stroke: CONNECTOR_STROKE,
      strokeWidth: CONNECTOR_STROKE_WIDTH,
    },
    {
      id: "planning-to-execution",
      from: { nodeId: "planning-kickoff", side: "right" },
      to: { nodeId: "execution-grooming", side: "left" },
      mode: "orthogonal",
      route: {
        pattern: "h-v-h",
        midX: 254,
      },
      stroke: CONNECTOR_STROKE,
      strokeWidth: CONNECTOR_STROKE_WIDTH,
    },
    {
      id: "execution-top",
      from: { nodeId: "execution-grooming", side: "right" },
      to: { nodeId: "execution-versioning", side: "left" },
      mode: "straight",
      stroke: CONNECTOR_STROKE,
      strokeWidth: CONNECTOR_STROKE_WIDTH,
    },
    {
      id: "execution-left-column",
      from: { nodeId: "execution-grooming", side: "bottom" },
      to: { nodeId: "execution-standups", side: "top" },
      mode: "straight",
      stroke: CONNECTOR_STROKE,
      strokeWidth: CONNECTOR_STROKE_WIDTH,
    },
    {
      id: "execution-right-column",
      from: { nodeId: "execution-versioning", side: "bottom" },
      to: { nodeId: "execution-sprint", side: "top" },
      mode: "straight",
      stroke: CONNECTOR_STROKE,
      strokeWidth: CONNECTOR_STROKE_WIDTH,
    },
    {
      id: "execution-bottom",
      from: { nodeId: "execution-standups", side: "right" },
      to: { nodeId: "execution-sprint", side: "left" },
      mode: "straight",
      stroke: CONNECTOR_STROKE,
      strokeWidth: CONNECTOR_STROKE_WIDTH,
    },
    {
      id: "execution-to-delivery-top",
      from: { nodeId: "execution-versioning", side: "right" },
      to: { nodeId: "delivery-qa", side: "left" },
      mode: "straight",
      stroke: CONNECTOR_STROKE,
      strokeWidth: CONNECTOR_STROKE_WIDTH,
    },
    {
      id: "delivery-column",
      from: { nodeId: "delivery-qa", side: "bottom" },
      to: { nodeId: "delivery-release", side: "top" },
      mode: "straight",
      stroke: CONNECTOR_STROKE,
      strokeWidth: CONNECTOR_STROKE_WIDTH,
    },
    {
      id: "execution-to-delivery-bottom",
      from: { nodeId: "execution-sprint", side: "right" },
      to: { nodeId: "delivery-release", side: "bottom" },
      mode: "orthogonal",
      route: {
        pattern: "h-v-h",
        midX: 1125,
      },
      stroke: CONNECTOR_STROKE,
      strokeWidth: CONNECTOR_STROKE_WIDTH,
    },
  ],
  legend: {
    x: 1100,
    y: 470,
    itemSize: 20,
    rowGap: 18,
    labelOffsetX: 33,
    items: [
      {
        id: "legend-waterfall",
        labelKey: "waterfall",
        theme: "waterfall",
      },
      {
        id: "legend-agile",
        labelKey: "agile",
        theme: "agile",
      },
    ],
  },
};

export const slide5LayoutPresets = {
  desktop: slide5DesktopLayoutPreset,
} as const;
