import type { Slide6LayoutPreset } from "./slide6Diagram.types";

const CONNECTOR_STROKE = "#A3A3A3";
const CONNECTOR_STROKE_WIDTH = 1;

export const slide6DesktopLayoutPreset: Slide6LayoutPreset = {
  id: "desktop",
  canvas: {
    width: 1230,
    height: 566,
  },
  nodes: [
    {
      id: "epic",
      x: 440,
      y: 0,
      w: 320,
      h: 96,
      theme: "dark",
      dotTone: "blue",
      typeLabelKey: "epic",
      bodyLabelKey: "epicBody",
      radius: 10,
    },
    {
      id: "story-left",
      x: 13,
      y: 207,
      w: 320,
      h: 96,
      theme: "light",
      dotTone: "dark",
      typeLabelKey: "story",
      bodyLabelKey: "storyLeftBody",
      radius: 10,
    },
    {
      id: "story-middle",
      x: 440,
      y: 207,
      w: 320,
      h: 96,
      theme: "light",
      dotTone: "dark",
      typeLabelKey: "story",
      bodyLabelKey: "storyMiddleBody",
      radius: 10,
    },
    {
      id: "story-right",
      x: 867,
      y: 207,
      w: 320,
      h: 96,
      theme: "light",
      dotTone: "dark",
      typeLabelKey: "story",
      bodyLabelKey: "storyRightBody",
      radius: 10,
    },
    {
      id: "ac-left",
      x: 13,
      y: 414,
      w: 160,
      h: 96,
      theme: "light",
      dotTone: "dark",
      typeLabelKey: "ac",
      bodyLabelKey: "acLeftBody",
      radius: 10,
    },
    {
      id: "bug-left",
      x: 203,
      y: 414,
      w: 160,
      h: 96,
      theme: "light",
      dotTone: "red",
      typeLabelKey: "bug",
      bodyLabelKey: "bugLeftBody",
      radius: 10,
    },
    {
      id: "ac-middle",
      x: 440,
      y: 414,
      w: 160,
      h: 96,
      theme: "light",
      dotTone: "dark",
      typeLabelKey: "ac",
      bodyLabelKey: "acMiddleBody",
      radius: 10,
    },
    {
      id: "bug-middle",
      x: 630,
      y: 414,
      w: 160,
      h: 96,
      theme: "light",
      dotTone: "red",
      typeLabelKey: "bug",
      bodyLabelKey: "bugMiddleBody",
      radius: 10,
    },
    {
      id: "ac-right",
      x: 867,
      y: 414,
      w: 160,
      h: 96,
      theme: "light",
      dotTone: "dark",
      typeLabelKey: "ac",
      bodyLabelKey: "acRightBody",
      radius: 10,
    },
    {
      id: "bug-right",
      x: 1057,
      y: 414,
      w: 160,
      h: 96,
      theme: "light",
      dotTone: "red",
      typeLabelKey: "bug",
      bodyLabelKey: "bugRightBody",
      radius: 10,
    },
  ],
  connectors: [
    {
      id: "epic-to-story-middle",
      from: { nodeId: "epic", side: "bottom", offset: 15 },
      to: { nodeId: "story-middle", side: "top", offset: 15 },
      mode: "straight",
      stroke: CONNECTOR_STROKE,
      strokeWidth: CONNECTOR_STROKE_WIDTH,
    },
    {
      id: "epic-to-story-left",
      from: { nodeId: "epic", side: "left", offset: 3 },
      to: { nodeId: "story-left", side: "top", offset: 27 },
      mode: "orthogonal",
      route: {
        pattern: "h-v-h",
        midX: 200,
      },
      stroke: CONNECTOR_STROKE,
      strokeWidth: CONNECTOR_STROKE_WIDTH,
    },
    {
      id: "epic-to-story-right",
      from: { nodeId: "epic", side: "right", offset: 3 },
      to: { nodeId: "story-right", side: "top", offset: 16 },
      mode: "orthogonal",
      route: {
        pattern: "h-v-h",
        midX: 1043,
      },
      stroke: CONNECTOR_STROKE,
      strokeWidth: CONNECTOR_STROKE_WIDTH,
    },
    {
      id: "story-left-to-ac-left",
      from: { nodeId: "story-left", side: "bottom", offset: 27 },
      to: { nodeId: "ac-left", side: "top", offset: 12 },
      mode: "orthogonal",
      route: {
        pattern: "v-h-v",
        midY: 355,
      },
      stroke: CONNECTOR_STROKE,
      strokeWidth: CONNECTOR_STROKE_WIDTH,
    },
    {
      id: "story-left-to-bug-left",
      from: { nodeId: "story-left", side: "bottom", offset: 27 },
      to: { nodeId: "bug-left", side: "top", offset: 12 },
      mode: "orthogonal",
      route: {
        pattern: "v-h-v",
        midY: 355,
      },
      stroke: CONNECTOR_STROKE,
      strokeWidth: CONNECTOR_STROKE_WIDTH,
    },
    {
      id: "story-middle-to-ac-middle",
      from: { nodeId: "story-middle", side: "bottom", offset: 15 },
      to: { nodeId: "ac-middle", side: "top" },
      mode: "orthogonal",
      route: {
        pattern: "v-h-v",
        midY: 355,
      },
      stroke: CONNECTOR_STROKE,
      strokeWidth: CONNECTOR_STROKE_WIDTH,
    },
    {
      id: "story-middle-to-bug-middle",
      from: { nodeId: "story-middle", side: "bottom", offset: 15 },
      to: { nodeId: "bug-middle", side: "top", offset: -3 },
      mode: "orthogonal",
      route: {
        pattern: "v-h-v",
        midY: 355,
      },
      stroke: CONNECTOR_STROKE,
      strokeWidth: CONNECTOR_STROKE_WIDTH,
    },
    {
      id: "story-right-to-ac-right",
      from: { nodeId: "story-right", side: "bottom", offset: 15 },
      to: { nodeId: "ac-right", side: "top" },
      mode: "orthogonal",
      route: {
        pattern: "v-h-v",
        midY: 355,
      },
      stroke: CONNECTOR_STROKE,
      strokeWidth: CONNECTOR_STROKE_WIDTH,
    },
    {
      id: "story-right-to-bug-right",
      from: { nodeId: "story-right", side: "bottom", offset: 15 },
      to: { nodeId: "bug-right", side: "top" },
      mode: "orthogonal",
      route: {
        pattern: "v-h-v",
        midY: 355,
      },
      stroke: CONNECTOR_STROKE,
      strokeWidth: CONNECTOR_STROKE_WIDTH,
    },
  ],
};

export const slide6LayoutPresets = {
  desktop: slide6DesktopLayoutPreset,
} as const;
