import type { LlmDay2026Content } from "./types";

export const llmDay2026Content = {
  brandLogo: {
    id: "ujcg-logo",
    src: "/panels/01-global/ujcg-logo-f3f3f3-65.svg",
    alt: "",
  },
  navigation: {
    previousAriaLabel: "Previous slide",
    nextAriaLabel: "Next slide",
    openTocAriaLabel: "Open slide table of contents",
    toggleFullscreenAriaLabel: "Toggle fullscreen",
    tocDialogAriaLabel: "Slide table of contents",
    tocTitle: "Slide Table of Contents",
    closeButtonLabel: "Close",
  },
  diagrams: {
    legacyRevenueFlow: {
      nodes: [
        { id: "node-311-call-center", label: "311 & Call Center" },
        { id: "node-customer-report-online", label: "Customer Report Online" },
        { id: "node-streetlight-alert", label: "Streetlight Alert" },
        { id: "node-ivr", label: "IVR" },
        { id: "node-create-sap-work-order", label: "Create SAP Work Order" },
        { id: "node-order-dispatch-crew", label: "Order Dispatch to Crew" },
        { id: "node-decision-simple-repair", label: "Decision: Simple Repair" },
        { id: "node-field-work-completed", label: "Field Work Completed" },
        { id: "node-outage-order-closed-mds", label: "Outage Order Closed (MDS)" },
        { id: "node-outage-order-closed-sap", label: "Outage Order Closed (SAP)" },
        { id: "node-follow-order-created", label: "Follow Order Created" },
        { id: "node-order-sent-tech-crew", label: "Order Sent to Tech Crew" },
        { id: "node-sap-work-order-created", label: "SAP W/O Created" },
      ],
      automationTargetNodeIds: [
        "node-311-call-center",
        "node-create-sap-work-order",
        "node-decision-simple-repair",
        "node-outage-order-closed-sap",
      ],
      automationLegendTitle: "Automation",
      automationLegendDescription:
        "White nodes indicate steps that can be executed or pre-validated by agents.",
      peopleLegendTitle: "People",
      peopleLegendDescription:
        "Dark nodes remain human-owned for judgment, exception handling, and approvals.",
    },
  },
  slideOrder: [
    "hero",
    "agenda",
    "who",
    "class101",
    "frame",
    "magicRequirements",
    "goal",
    "dontDoThis",
    "doThis",
    "howToDoThis",
    "examplesIntro",
    "clay",
    "systemArchitecture",
    "placeholderTwo",
    "placeholderGeneric",
    "complianceWorkflow",
    "okgo",
    "directvManual",
    "rubeGoldberg",
    "aiAmplified",
    "placeholderEight",
    "flowchartAutomated",
    "flowchartManual",
    "close",
    "interviewThankYou",
  ],
  slides: {
    hero: {
      id: "slide-main-title",
      title: "Designing LLM Workflows",
      highlight: "That Drive Enterprise ROI",
      eyebrow: "Keynote Presentation",
      presenter: "By: Jim Markunas",
      sponsor: "Sponsored by: LLM Day Austin 2026",
    },
    agenda: {
      id: "slide-agenda",
      title: "What We’ll Cover in This Talk",
      subtitle: "Copilots vs Agents: Driving ROI in your organization.",
      whyCareLabel: "Why you care:",
      bullets: [
        { id: "agenda-copilot-vs-agent", text: "Copilots vs Agents" },
        {
          id: "agenda-roi",
          text: "How to make them drive ROI in your organization",
        },
        {
          id: "agenda-pm-examples",
          text: "Real Examples of C+ vs. A+ Product Management",
        },
      ],
      whyCare: [
        { id: "01", label: "Make AI drive revenue (the Holy Grail)" },
        {
          id: "02",
          label: "Be the best in your industry by leveraging AI tools",
        },
        { id: "03", label: "Think differently + Change the game" },
      ],
    },
    who: {
      id: "slide-who",
      title: "Who I Am",
      subtitle: "Diagnose like an architect, prioritize like a product owner, and deliver like a PM.",
      companies: {
        label: "Companies I've Helped",
        logos: [
          { id: "aa", src: "/panels/02-interview/aa-logo-int.svg", alt: "American Apparel" },
          { id: "bcg", src: "/panels/02-interview/bcg-logo-int.svg", alt: "BCG" },
          { id: "burton", src: "/panels/02-interview/bc-logo-int.svg", alt: "Burton" },
          { id: "directv", src: "/panels/02-interview/dtv-logo-int.svg", alt: "DIRECTV" },
          { id: "disney", src: "/panels/02-interview/disney-logo-int.svg", alt: "Disney" },
          { id: "hbo", src: "/panels/02-interview/hbo-logo-int.svg", alt: "HBO" },
          {
            id: "publicis-sapient",
            src: "/panels/02-interview/publicis-sapient-logo-int.svg",
            alt: "Publicis Sapient",
          },
          { id: "shopify", src: "/panels/02-interview/shopify-logo-int.svg", alt: "Shopify" },
        ],
      },
      stats: [
        { id: "stat-20-years", label: "20+ Years", sub: "Leading Digital Delivery" },
        { id: "stat-75-projects", label: "75+", sub: "Projects Led" },
        { id: "stat-40k-hours", label: "40k Hrs.", sub: "PM Experience" },
        { id: "stat-roi", label: "$1.3B", sub: "ROI Delivered" },
      ],
    },
    class101: {
      id: "slide-101-class",
      title: "The 101 Class",
      line: "Key concepts for digital transformation",
    },
    frame: {
      id: "slide-frame",
      title: "Copilot vs Agent",
      copilotTitle: "Copilot",
      agentTitle: "Agent",
      copilot: ["Answers your question", "You drive", "One interaction"],
      agent: [
        "Takes action across your systems",
        "It drives",
        "Ongoing workflow",
      ],
      kickerPrefix: "The difference isn’t the model.",
      kickerHighlight: "It’s the workflow design.",
    },
    magicRequirements: {
      id: "slide-magic-requirements",
      title: "The 3 Magic Requirements",
      subtitle: "Every AI workflow needs...",
      items: [
        {
          id: "requirement-01",
          label: "Requirement 01",
          title: "Guardrails",
          desc: "Define the failure mode before you build",
        },
        {
          id: "requirement-02",
          label: "Requirement 02",
          title: "Escalation Paths",
          desc: "A human who owns exceptions",
        },
        {
          id: "requirement-03",
          label: "Requirement 03",
          title: "Measurable Outcome",
          desc: "Quantify, Quantify, Quantify",
        },
      ],
    },
    goal: {
      id: "slide-goal",
      title: "Goal",
      line: "Think about it backwards",
    },
    dontDoThis: {
      id: "slide-dont-do-this",
      title: "Don’t Do This",
      subtitle: "Most executives think about AI completely backwards",
      items: [
        {
          id: "dont-01",
          text: "AI is plug-and-play. Just buy it, Mr. CTO, we’ll be rich!",
        },
        {
          id: "dont-02",
          text: "AI will reduce costs quickly. We’ll be even richer!",
        },
        {
          id: "dont-03",
          text: "AI can replace my whole staff. We’ll be even more rich!",
        },
        {
          id: "dont-04",
          text: "None of that worked, so let’s do silent layoffs to inflate the stock.",
        },
      ],
      footer: "Common Pitfalls in AI Strategy",
    },
    doThis: {
      id: "slide-do-this",
      title: "Do This",
      subtitle: "Start with a goal, then reverse engineer",
      items: [
        {
          id: "do-01",
          text: "I want to increase customer retention by 50% + upsell them.",
        },
        {
          id: "do-02",
          text: "I want an AI agent that measures behavior and tells us how to target customers automatically.",
        },
        {
          id: "do-03",
          text: "We’re currently paying for Salesforce, Snowflake, and Tableau.",
        },
        { id: "do-04", text: "Let’s architect an intentional solution." },
      ],
      footer: "The Intentional AI Roadmap",
    },
    howToDoThis: {
      id: "slide-how-to-do-this",
      title: "How to Do This",
      subtitle: "The smart operator builds something like this",
      explainerTitle: "How This Workflow Operates",
      explainerPoints: [
        "Salesforce, Snowflake, and Tableau feed behavior signals into a daily churn monitor so risk is detected before cancellation happens.",
        "The offer engine selects the best next action for each at-risk account, then the action agent either executes outreach or routes to human escalation.",
        "Every result writes back to Salesforce, closes the feedback loop, and continuously improves retention targeting over time.",
      ],
      platformCards: [
        {
          id: "platform-salesforce",
          title: "Salesforce CRM",
          subtitle: "contacts, cases, activity",
        },
        {
          id: "platform-snowflake",
          title: "Snowflake",
          subtitle: "usage, billing, history",
        },
        {
          id: "platform-tableau",
          title: "Tableau",
          subtitle: "retention dashboards",
        },
      ],
      agentCards: [
        {
          id: "agent-churn",
          title: "Churn Monitor Agent",
          subtitle: "scores risk daily, flags accounts",
        },
        {
          id: "agent-offer",
          title: "Offer Engine Agent",
          subtitle: "matches segment to best offer",
        },
        {
          id: "agent-action",
          title: "Action Agent",
          subtitle: "triggers outreach or escalates",
        },
      ],
      outputCards: [
        {
          id: "output-retained",
          title: "Retained Customer",
          subtitle: "offer accepted, case closed",
        },
        {
          id: "output-escalation",
          title: "Human Escalation",
          subtitle: "complex or high-value case",
        },
      ],
      diagram: {
        platformColumnLabel: "Platforms",
        agentColumnLabel: "Agents",
        outputColumnLabel: "Output",
        outcomeLabel: "Outcome written back to Salesforce",
      },
      guardrailLabel: "Guardrail: confidence gate",
      footer: "Architecting for Enterprise ROI",
    },
    examplesIntro: {
      id: "slide-examples-intro",
      title: "Examples",
      line: "Turn C+ work to A+ w/ AI",
      subline: "(win clients, get promoted, change the world, get filthy rich)",
    },
    clay: {
      id: "slide-clay",
      title: "Rule #1: Don’t Be Clay",
      subtitle: "Because Clay’s phone never rings...",
      caption: "Wanna know why his phone never rings?",
      diagram: {
        label: "Pipeline",
        state: "Idle",
        description:
          "Great people still lose momentum when workflow design is weak.",
      },
    },
    systemArchitecture: {
      id: "slide-architecture",
      title: "New York Life Compliance-Driven CMS",
      subtitle: "A project so boring, the client ghosted the agency like a Tinder date..",
      flowLabel: "System Architecture Flow",
      roles: [
        {
          id: "role-back-office",
          title: "Back Office",
          tag: "CREATE CONTENT",
          desc: "Primary content creators responsible for drafting and initial system entries.",
        },
        {
          id: "role-field-agents",
          title: "Field Agents",
          tag: "REQUEST CHANGES",
          desc: "Regional representatives who initiate change requests and localized updates.",
        },
        {
          id: "role-home-office",
          title: "Home Office",
          tag: "REVIEW & PUBLISH",
          desc: "The ultimate authority for quality assurance and production deployment.",
        },
      ],
      flowNodes: [
        { id: "flow-01", step: "01", title: "Draft", sub: "CREATION" },
        { id: "flow-02", step: "02", title: "Submit", sub: "VALIDATION" },
        { id: "flow-03", step: "03", title: "Review", sub: "QA ANALYSIS" },
        { id: "flow-04", step: "04", title: "Decision", sub: "AUTHORIZATION" },
        {
          id: "flow-05",
          step: "05",
          title: "Publish",
          sub: "PRODUCTION",
          emphasized: true,
        },
      ],
    },
    placeholderTwo: {
      id: "slide-placeholder-13-mid",
      title: "We Got Decent Results, But...",
      subtitle: "The client didn't care about our C- product",
    },
    placeholderGeneric: {
      id: "slide-placeholder-new-14",
      title: "NYL CDO Bragged to the Press",
      subtitle: "About everyting except our work",
    },
    complianceWorkflow: {
      id: "slide-compliance-workflow",
      title: "What Would the A+ Look Like?",
      subtitle: "Automated governance with human-in-the-loop selection.",
      steps: [
        {
          id: "step-01",
          type: "AI AGENT",
          title: "Dual-Agent Drafting",
          desc: "Marketing + Legal AI agents collaborate on initial drafts.",
        },
        {
          id: "step-02",
          type: "AI AGENT",
          title: "Legal Viability Check",
          desc: "Cross-referenced against regulations and historical cases.",
        },
        {
          id: "step-03",
          type: "PERSON",
          title: "Salesperson Selection",
          desc: "NYL agents select approved content for their digital presence.",
        },
        {
          id: "step-04",
          type: "AI AGENT",
          title: "Instant Publishing",
          desc: "Final compliance re-vetting and immediate deployment.",
        },
        {
          id: "step-05",
          type: "AI AGENT",
          title: "Home Office Logging",
          desc: "Immutable audit trail and notification to Home Office.",
        },
      ],
      legend: [
        { id: "legend-automated-oversight", label: "Automated Oversight" },
        { id: "legend-human-loop", label: "Human-in-the-loop" },
        { id: "legend-full-auditability", label: "Full Auditability" },
      ],
    },
    okgo: {
      id: "slide-okgo",
      title: "Rule #2: Don’t Be OKGo",
      subtitle: "The guys who did the treadmill video",
      caption: "They also made a Rube Goldberg Machine video",
      diagram: {
        label: "Complexity",
        state: "High",
        description:
          "Clever systems can still become brittle when every step depends on another manual step.",
      },
    },
    flowchartManual: {
      id: "slide-flowchart",
      title: "Award-Winning Work",
      subtitle: "That stemmed from a real problem",
      bullets: [
        "Turned a negative news story into a public victory",
        "Won an international award",
        "Set the standard for green tech streetlights worldwide",
      ],
      imageSrc: "/interviews/llmday/smart-20-logo-600.png",
      imageAlt: "Smart 20 award logo",
    },
    flowchartAutomated: {
      id: "slide-flowchart-automated",
      title: "CPS Energy's Automated Streetlights",
      subtitle: "Automation that added value & won on the global stage",
    },
    directvManual: {
      id: "slide-directv-manual",
      title: "DIRECTV Manual Revenue Engine",
      subtitle: "$120M in uplift, every report built by hand.",
      modules: [
        { id: "module-cohorts", label: "Cohorts" },
        { id: "module-campaign-math", label: "Campaigns" },
        { id: "module-stb-push", label: "STB Push" },
        { id: "module-reporting", label: "Reporting" },
      ],
      moduleStatusLabel: "Status: Manual",
      quote:
        "A revenue engine held together by people doing repetitive knowledge work.",
    },
    rubeGoldberg: {
      id: "slide-rube-goldberg",
      title: "Revenue Engine Meets Rube Goldberg",
      subtitle: "Generating ROI was painful",
      caption: "Visualizing operational complexity",
      chips: [
        "Manual Hand-off",
        "Spreadsheet Reconciliation",
        "Approval Chain",
        "Data Quality Patch",
        "Last-mile Intervention",
        "Executive Reporting",
      ],
    },
    aiAmplified: {
      id: "slide-ai-amplified",
      title: "Where AI Could Have Amplified DTV",
      subtitle: "What I’d scope: three agents, one revenue engine.",
      agents: [
        {
          id: "ai-martech",
          title: "Martech Agent",
          desc: "Tracks customers and assets, alerts on launch risk, and routes campaign suggestions through governance.",
          tone: "blue",
        },
        {
          id: "ai-billing-config",
          title: "Automated Billing + Config Agent",
          desc: "Builds campaign metadata automatically across platforms and systems.",
          tone: "violet",
        },
        {
          id: "ai-reporting",
          title: "Reporting Agent",
          desc: "Reads the data lake and surfaces risk/opportunity signals like: 40K subs at risk, Paramount+ at 3.4x.",
          tone: "green",
        },
      ],
      footer: "The Future of Operational Efficiency",
    },
    placeholderEight: {
      id: "slide-placeholder-19",
      title: "Rule #3: Be a Meccan",
      subtitle: "The smallest Texas major hits the global stage",
    },
    designPattern: {
      id: "slide-design-pattern",
      title: "Build ROI Into Your Workflows",
      footer: "The Blueprint for AI Success",
      diagram: {
        step01Label: "Step 01",
        step01Title: "TRIGGER",
        step02Label: "Step 02",
        step02Title: "AGENT ACTION",
        step02Subtitle: "LLM reasons, retrieves, drafts",
        step03Label: "Step 03",
        step03Title: "DECISION GATE",
        step03Subtitle: "Confidence threshold met?",
        pathALabel: "Path A",
        pathATitle: "AUTO-COMPLETE",
        pathBLabel: "Path B",
        pathBTitle: "HUMAN ESCALATION",
        pathBSubtitle: "review, approve, override",
        step04Label: "Step 04",
        step04Title: "LOG + MEASURE OUTCOME",
        step04Subtitle: "cycle time · error rate · throughput",
        requirements: [
          {
            id: "req-01",
            label: "Requirement 01",
            lead: "Decision Gate",
            detail: " = the guardrail",
            caption: "define failure mode first",
          },
          {
            id: "req-02",
            label: "Requirement 02",
            lead: "Human Escalation",
            detail: " = design feature, not failure",
          },
          {
            id: "req-03",
            label: "Requirement 03",
            lead: "Log + Measure",
            detail: " = how you justify the next one",
          },
        ],
      },
    },
    close: {
      id: "slide-close",
      title: "The Agent Era Needs Innovators",
      introPrefix: "The copilot era needed",
      introHighlight: "prompt engineers",
      skillsIntro: "The agent era needs people who can:",
      points: [
        "Define metrics",
        "Build the human override before the automation",
        "Sequence the workflow across systems & teams",
        "Measure whether it’s working",
      ],
      quote:
        "Agents don’t fail because the model is bad.\n\nThey fail because nobody designed the end goal.",
      footerLeft: "Designing LLM Workflows That Drive Enterprise ROI",
      footerRight: "",
    },http://localhost:3000/
    
    interviewThankYou: {
      id: "slide-interview-thank-you",
      title: "Thank You",
      subtitle: "Let's build something extraordinary.",
      name: "Jim Markunas",
      role: "Greatest PM Ever",
      email: "jim@greatestpmever.com",
      linkedin: "linkedin.com/in/jimmarkunas",
      readyText: "Ready for Questions",
    },
  },
} satisfies LlmDay2026Content;
